- change_log.txt
- includes/steps/class-step-feed-user-registration.php
- Adds support for manual activations.
- Assigns the entry to the newly created user automatically.
> User Registration Step enhancements

- includes/steps/class-step-user-input.php
- fix post image merge tags for existing images
- remove the fields old post image when a new image is saved to the
entry
> Fix two issues with post images

- .travis.yml
- Adapt PHPUnit version to PHP version.
- Cache node_modules
- Add debugging info
> Build script enhancements

- change_log.txt
- class-gravity-flow.php
- includes/steps/class-step.php
Adds the date field option to the step expiration setting.
> add date field option to expiration setting

- includes/pages/class-support.php
- Fixes a few untranslatable strings
- Sends the system report available with GF2.2+ when send debug info is enabled
> Support page updates

- class-gravity-flow.php
- includes/class-common.php
- includes/models/class-activity.php
- includes/pages/class-status.php
add support for Gravity Forms 2.3
> Gforms 2.3 compatibility

- class-gravity-flow.php
- includes/pages/class-entry-detail.php
- includes/pages/class-support.php
adds an admin notice when the SCRIPT_DEBUG constant is not set for the dev version
> add nag for dev version

- change_log.txt
- class-gravity-flow.php
Make the cancelled option available in entry filters.
> add cancelled final status option to entry meta

- class-gravity-flow.php
- includes/steps/class-step-approval.php
- includes/wizard/steps/class-iw-step-license-key.php
Some l10n/i18n code improvements provided by our WP-T Teams
> WP-T improvements

- change_log.txt
- includes/steps/class-step.php
Adds the gravityflow_step_assignees filter. [Example](https://github.com/gravityflow/gravityflowlibrary/blob/master/expand-roles-to-users.php).
> add the gravityflow_step_assignees filter

- .travis.yml
- change_log.txt
- class-gravity-flow.php
- includes/steps/class-step-webhook.php
- tests/bootstrap.php
Adds PATCH to the list of request methods in the request method setting of the Outgoing Webhook step settings.
Adds Headers to the Outgoing Webhook step settings.
Adds the Raw body setting to the OUtgoing webhook step settings.
> add raw body and headers settings

- includes/pages/class-entry-editor.php
- includes/steps/class-step-feed-add-on.php
The min GF version is now 2.1 so let's remove the few lines which are no longer needed.
> Remove code for GF versions older than 2.1

- includes/steps/class-step-webhook.php
Implements Basic Auth for Gravity Flow suitable for Basic Auth plugin for WP Api - ref https://github.com/WP-API/Basic-Auth
> Basic Auth for Gravity Flow Outgoing Webhook

- css/frontend.css
[HS4546](https://secure.helpscout.net/conversation/433879139/4546?folderId=516732)
> Fix for narrow screens

- change_log.txt
- includes/steps/class-step-feed-slicedinvoices.php
Adds the sent status of a sliced invoice.
> Add invoice sent status

- change_log.txt
- class-gravity-flow.php
re: [HS#4881](https://secure.helpscout.net/conversation/472450103/4881/?folderId=793490)
Adds a filter allowing the site cookie path to be overridden.
> Added gravityflow_site_cookie_path filter

- readme.txt
> bump gf version

- class-gravity-flow.php
Ensure cron tasks are not run while upgrade is in progress.
> Block cron during submission block

- change_log.txt
- css/discussion-field.css
- css/entry-detail.css
- css/feed-list.css
- css/form-settings.css
- css/frontend.css
- css/inbox.css
- css/multi-select.css
- css/settings.css
- css/status.css
Create RTL version for CSS selectors contain attributes like: text-align, float, clear, right/left margin/padding/position/border etc.
See screenshots for before (left) & after (right). Admin:
Front end:
> CSS RTL improvements

- includes/pages/class-status.php
- Bug Fix - Form column was displaying form id, now showing form title to match status screen.
- Enhancement - Re-uses gravityflow_field_value_status_table filter to display custom columns
> 5092 status export columns

- class-gravity-flow.php
- includes/steps/class-step-feed-slicedinvoices.php
Version 1.10 of the Sliced Invoices add-on, released several months ago, implemented the invoice/quote status and use product field settings. 
As our step was already implementing these settings on their edit feed page we should remove our versions of them to reduce any confusion for users configuring the Sliced Invoices feeds.
As the settings use different names this also updates the feed meta in the database to use the Sliced Invoices setting names instead of ours.
> Remove duplicate settings from Sliced Invoices feeds

- change_log.txt
- class-gravity-flow.php
- includes/steps/class-step-approval.php
Adds the current step as parameters to the gravityflow_feedback_approval_token and gravityflow_feedback_approval filters.
Adds the gravityflow_feedback_cancel_workflow filter.
> Update feedback filters

- change_log.txt
- includes/pages/class-inbox.php
**To test:**
- Add filter to gravityflow_inbox_paging which returns:
```
$paging  = array(
'page_size' => 5,
);
```
- Note how the inbox returns limited results
> 5466 inbox entries

- change_log.txt
- class-gravity-flow.php
- css/feed-list.css
- js/feed-list.js
**Settings List / Edit Screens show Step ID #**
**How to test:**
- View Workflow Settings screen
- Note Step ID # as new column
- Click on an individual step to edit
- Note the Step ID # is added to sub-heading area (previously just "Step")
> Add Step ID # to workflow settings list and edit step screens

- change_log.txt
- includes/steps/class-step-approval.php
- includes/steps/class-step.php
The recent assignee refactor works only for the User Input step. This PR adds support also for the Approval step.
On master
- add the following snippet to add a dept assignee:
https://gist.github.com/stevehenty/dc73ca8c9501d11f28419ce92399aa3b
- add the department as an assignee of an approval step
- submit the form and reach the approval step
- when approving or rejecting the step status doesn't change  making it impossible to complete the step
On this branch
- the approval step works correctly both from the workflow detail page and from the quick actions column on the inbox
> Fix status update for recent assignee refactor

- class-gravity-flow.php
re: [HS#5975](https://secure.helpscout.net/conversation/576374874/5975?folderId=1113497)
>  Fixed fatal error if entry is deleted before the workflow starts

- change_log.txt
- includes/assignees/class-assignee.php
This PR fixes the notification ID for assignee notifications.
> Fix notification id

- change_log.txt
- css/discussion-field.css
- css/entry-detail.css
- css/form-settings.css
- css/frontend.css
- css/inbox.css
- includes/pages/class-print-entries.php
This PR fixes the same issue as PR #143, furthermore, it fixes general RTL CSS bugs that left/right margin or padding isn't reset correctly.
> Fix RTL CSS issues

- change_log.txt
- css/frontend.css
Fixes some styling issues in the front end inbox and status pages with the Twentyseventeen theme.
> Fix styles

- class-gravity-flow.php
This PR fixes an issue with the status page shortcode where the workflow_info and step_status attributes are ignored.
> Fix status shortcode attributes

- change_log.txt
- class-gravity-flow.php
This PR adds the `gravityflow_feed_condition_entry_properties` filter to allow modifying entry properties in the feed condition.
The testing instructions will be demonstrated in another PR from the WooCommerce extension later.
> Add gravityflow_feed_condition_entry_properties filter

- change_log.txt
- includes/steps/class-step-feed-post-creation.php
Updates the post creation step to support the new class name used by the add-on.
> Add support for the Gravity Forms Advanced Post Creation Add-On

- class-gravity-flow.php
- includes/steps/class-common-step-settings.php
- includes/steps/class-step.php
- js/form-settings.js
Still a WIP. I want to more thoroughly test both the upgrade routine and the multi-PDF sending code.
Let me know if there's a better way to access the PDF checkbox settings for a step.
> Allow multiple Gravity PDFs to be sent with a single notification

- class-gravity-flow.php
- includes/class-extension.php
- includes/class-feed-extension.php
This PR fixes spikes in licensing requests by spreading them out randomly over the day.
> Fix spikes in licensing requests

- includes/steps/class-step-feed-wp-e-signature.php
re: [HS#7750](https://secure.helpscout.net/conversation/761521590/7750?folderId=1113535)
The Signature add-on by ApproveMe can override the form confirmation, redirecting to the document to be signed, or send an email with a link. We currently force the email action to be used when the step processes the feed but as we now start the workflow before the gform_confirmation filter is triggered the redirect action could be used.
This PR adds a new method to the wp-e-signature step which determines if the redirect is supported at the time the step is triggering feed processing.
- Import test form: https://www.dropbox.com/s/pu3cfs5dosjw3wt/wp-e-signature.json?dl=0
- Configure a WP E-Signature add-on feed with the Signing Logic set to redirect
- Update the approval and signature step assignees …
> Allow wp e-signature redirect if processed before confirmation displayed

- class-gravity-flow.php
This fixes an issue where workflows don't start when the entry is created before the init action.
> Move gform_post_add_entry to pre_init

- class-gravity-flow.php
Adds a security setting to allow field values to be displayed using the shortcode.
> Add allow field values setting

- includes/steps/class-step-workflow-complete.php
Change the complete settings icon to a checkered flag.
> Change the complete icon to a checkered flag

- gravityflow.php
- includes/integrations/class-partial-entries.php
- readme.txt
Addresses [HS8641](https://secure.helpscout.net/conversation/816214581/8641?folderId=516726)
Fixes a fatal error when displaying the start settings when the Partial Entries Add-On is not active.
> Fix check for Partial Entries

- includes/steps/class-step-feed-dropbox.php
re: [HS#8527](https://secure.helpscout.net/conversation/808791197/8527?folderId=1113535)
Updates the Dropbox step to:
- Support expiration
- Only pass the feed to the Dropbox add-on if there are files to process
- Complete the step immediately when there are no files to process
- Follow testing instructions on the ticket to replicate the issue
- Repeat test and find that the step completes
> Fix workflow stalling on the Dropbox step when there are no files to process

- class-gravity-flow.php
Adds support for the back link attributes to the status shortcode.
> Add back link to status shortcode

- change_log.txt
- class-gravity-flow.php
- readme.txt
Fixes an issue with the confirmation page for users with the gravityflow_status_view_all capability when transitioning steps.
> Fix capability typo

- includes/pages/class-entry-detail.php
Fixes the display fields after submission of a user input step. 
See [HS9204](https://secure.helpscout.net/conversation/851293970/9204?folderId=516732) for details and testing instructions.
> Fix display fields after POST

- class-gravity-flow.php
Adds the gravityflow_can_render_form filter to the submit page so the form connector can display forms on the form submission step.
> Add gravityflow_can_render_form filter

- includes/merge-tags/class-merge-tag-created-by.php
- tests/unit-tests/test-merge-tags.php
As discussed.
Unit test included.
> Fix an issue with the created_by merge tag

- change_log.txt
- js/entry-detail.js
- js/status-list.js
Re: [HS# 15018](https://secure.helpscout.net/conversation/1301980605/15018?folderId=1113492#thread-3748435873)
The popup 'An error occurred while printing' comes up with Firefox when the Print button is clicked on the Workflow Details Page, along with other JS errors.
1. For workflow entries, check there are no Print issues on all browsers.
2. For front-end pages, check there are no Print issues on all browsers.
3. Confirm no JS errors reported on console associated with the Print execution.
N/A
N/A
N/A
> Fix errors print workflow
