includes/steps/class-step-approval.php, includes/steps/class-step-notification.php, includes/steps/class-step.php
Notable changes include:
- Greatly simplifying the PDF generation command
- Tweak the checks used when using the GPDFAPI (is_wp_error is preferred)
- Updated version check to ensure commands aren't run on a version of Gravity PDF that doesn't support them
- Ensured v3 compatibility isn't run when using v4.
Note: Gravity PDF 4.0 RC2 has not yet been released to our testers. It's currently in development.
=> Update the code so it's fully compatible with Gravity PDF 4.0 RC2

includes/pages/class-status.php
When retrieving the counts for the workflow status page, if no workflow form IDs are found, a new standard results class is created setting the result counts to 0. However, the total result count is not set and throws a PHP undefined property notice on the workflow status page.
=> Fixed undefined property notice on status page

change_log.txt, class-gravity-flow.php, includes/steps/class-common-step-settings.php
- Fixes authentication for single views when an assignee is defined in the Advanced Filter criteria. 
- Fix an issue where entries added by GFAPI don't have a final status set
- Fix the default text for the email assignee checkbox label
=> Fix gravityview single entry view

change_log.txt, class-gravity-flow.php, includes/pages/class-entry-detail.php
- Added validation for the checkbox and textbox setting.
- Added the gravityflow_sanitize_instructions filter.
- Removed wp_kses_post() from the instructions output.
=> Instructions unfiltered html

includes/class-web-api.php
The assignee key sent in the URL is urlencoded causing the update of the status via the Web API to fail.
=> urldecode the assignee key

change_log.txt, includes/steps/class-step-feed-slicedinvoices.php, includes/steps/class-step.php
- Added the Line Items setting
When enabled the entry product fields will be used to set the line items on the created invoice/estimate.
- Added the Assign To, Assignee Email, Instructions, and Display Fields settings.
- Added the 'Step Completion' setting
The step will complete immediately following feed processing unless the completion setting is set to delayed and the feeds created invoices. When set to delayed the step will have a status of pending until the invoices are paid.
- Added invoices to the workflow detail box
When step completion is delayed pending invoice payment the invoices will be listed in the workflow detail box for the step. Details include the invoice title or the feed name, the invoice number, the invoice total, the invoice status, and a preview button.
- Changed …
=> Sliced Invoices enhancements

class-gravity-flow.php, includes/steps/class-step-approval.php, includes/steps/class-step-user-input.php, js/form-settings.js
- add support for the assignee policy when conditional assignee routing is enabled.
- upgrade settings to ensure the default value is correct
- replace the unanimous_approval setting with the assignee_policy setting for consistency
=> add assignee policy enhancements

includes/pages/class-status.php
This allows more extensibility by developers who want to give more form-specific information for each row. The name and filter structure were borrowed from the 'gform_entries_field_value' filter in the Inbox table.
=> Allow filtering of most columns in the status table

class-gravity-flow.php
Remove reliance on `$_SERVER` variables to determine protocol and site URL and use WordPress' in-built `home_url()` method instead (`home_url()` will point to the front end WordPress site, rather than where the WordPress files are located - `site_url()`)
=> Fix redirect bug when incorrect HTTP_HOST is passed / set (this is user supplied)

class-gravity-flow.php, includes/class-assignee.php, includes/steps/class-step.php
Currently, the one-click tokens for roles don't include the ID of the user. This PR allows the tokens for role assignee to include the user ID. See [HS#4131](https://secure.helpscout.net/conversation/397448673/4131/?folderId=516732). It also opens the way for a {assignee:[meta_key]} merge tag like the {created_by} merge tag.
=> add user to assignee

change_log.txt, includes/pages/class-entry-editor.php
re: [HS#4202](https://secure.helpscout.net/conversation/402995135/4202/?folderId=793490)
Fixes empty fields being displayed on the user input step when 'show empty fields' is not checked.
=> fixed empty fields being displayed

includes/steps/class-step.php
Noticed this issue when using the Notification step with multiple assignees and only one email was going out.
=> Swap `return` to `continue` so all assignee's in the loop can be processed

includes/steps/class-step-user-input.php
Reloading the page after submitting a User Input step can complete the next User Input step. I couldn't reproduce the issue on any browser in OSX but I reproduced the issue in Microsoft Edge on Windows 10. This PR adds a check for the current step ID just before processing the status update. [HS#4218](https://secure.helpscout.net/conversation/404986229/4218/?folderId=516731)
=> check current step before processing status update

change_log.txt, class-gravity-flow.php, includes/pages/class-entry-detail.php, includes/pages/class-print-entries.php, includes/pages/class-status.php
The gravityflow_permission_granted_entry_detail and gravityflow_status_filter filters aren't firing for shortcodes and admin UI when the gravityflow_status_view_all cap is set.
=> Fix filters when gravityflow_status_view_all cap is set

change_log.txt, includes/merge-tags/class-merge-tag-workflow-note.php
re: [HS#4305](https://secure.helpscout.net/conversation/412406037/4305/?folderId=516726)
When using the step_id modifier with the workflow_note merge tag all the user submitted notes with the specified step id will be returned. For the average workflow that is fine, however, if the workflow includes loops so a step can occur multiple times the notes from all occurrences are currently output.
The all_occurrences modifier when set to false will return only those notes belonging to the most recent occurrence of the specified step.
=> Add modifier to limit user notes to most recent occurrence of the specified step

change_log.txt, includes/steps/class-step-feed-dropbox.php
In Dropbox 2.0 the class name changed from GFDropbox to GF_Dropbox. This change has caused Dropbox steps to fail the `class_exits()` check in `Gravity_Flow_Step_Feed_Add_On::is_supported()` so existing steps would not run during the workflow and new steps could not be created.
=> Fix Dropbox Steps for Dropbox 2.0+

class-gravity-flow.php, css/frontend.css, includes/class-extension.php, includes/class-feed-extension.php, includes/pages/class-status.php
- Updates min requirements to work with Gravity Forms 2.3 which uses admin messages instead of displaying the messages on the settings tab.
- Updates the status page to display admin messages above the toolbar like other pages whilst keeping the bulk action messages in their existing location below the filters. This change also fixes an issue where the bulk action message would not be displayed if an admin message is present.
- Fixes an issue where the status page bulk action messages are hidden on the front-end by the Twenty themes.
=> Fix min requirements for GF2.3

includes/steps/class-step-user-input.php
This ensures new user input steps for forms with conditional logic fields or pages have the 'Enable field conditional logic' checkbox active by default. Does not impact existing user input steps that had already stored value on / off.
=> Fix User Step default_value for field conditional logic

change_log.txt, includes/steps/class-step-feed-hubspot.php
This updates the step to support the namespaced class name introduced in version 3.0 of the HubSpot for Gravity Form plugin.
=> Fix the Hubspot step

change_log.txt, includes/steps/class-step.php
Fixes an issue with the timeline notes for Approval and User Input steps where the step icon is used instead of the user avatar.
=> Fix assignee notes

includes/class-assignee.php
Updated the cache key used when getting the assignee status to support the blog id prefix introduced in Gravity Forms 2.3-beta-3.
=> Added support for GF2.3 $_gform_lead_meta change

change_log.txt, includes/pages/class-entry-editor.php
re: [HS#4878](https://secure.helpscout.net/conversation/472255809/4878?folderId=793490)
GFFormsModel::is_field_hidden() was returning true for the section field as the two rules for display were not met. This caused Gravity_Flow_Entry_Editor::is_display_field() to return false which resulted in the section fields conditionalLogicFields and conditionalLogic properties being set to null so the section was displayed.
This change prevents GFFormsModel::is_field_hidden() being used for section fields in Gravity_Flow_Entry_Editor::is_display_field(). The section logic will be evaluated when the gform_field_container filter runs later.
=> fixed ui step section field logic

change_log.txt, class-gravity-flow.php, tests/acceptance-tests/_data/forms/0020-step-status-conditional-logic.json, tests/acceptance-tests/acceptance/0020StepStatusConditionalLogicCept.php
When using "step status" as feed condition, Gravity Flow doesn't update the feed IDs after importing the form. That makes all steps with such conditions skipped.
To reproduce this issue, create two steps and set the "Feed Condition" for the second step to depend on "if Status: First Step is Approved." Export the form and import it again. Should see the field ID (Status: First Step) missing.
These commits come with an acceptance test to validate it has been fixed.
=> Fix feed IDs (step IDs) in feed condition

css/entry-detail.css, includes/steps/class-step-user-input.php
This extends the user input step type Save Progress option drop-down with an additional 'Two Button' type. It displays two form submit buttons for Save Progress and Submit instead of the radio + form submit button.
Two areas where review/feedback is useful:
1. **Filters in display_update_button** - Whether should match the filter types (field label and entire button) of the other scenarios and/or apply same filters - like gravityflow_update_button_text_user_input - which have "identical" purpose.
1. **maybe_enable_update_button** - Whether this approach of enabling non-existent buttons is ok/preferred vs checking for save progress option and separate script tag blocks.
=> Save Progress - Add Submit Button option + logic

class-gravity-flow.php
Attributes in [The Shortcode docs](http://docs.gravityflow.io/article/36-the-shortcode) for Inbox / Status will need to be updated to include entry_id. Noting that any page where lid is in querystring params takes precedence over the shortcode attribute.
=> Add entry_id attribute for shortcode for inbox / status to direct link

includes/pages/class-inbox.php
The filter gravityflow_inbox_args provides method to limit the shortcode to an array of forms. But the check whether to display Form Name as column in the inbox assumes the form_id argument is empty. This PR expands it to also check/allow array values to trigger Form Name column display.
https://gist.github.com/Idealien/aaeb8538adcf28d16f721ca4c44f249b is example of filter use that would not  display Form Name column without the PR.
=> Enabling Form Title column for Inbox with multiple forms set via the gravityflow_inbox_args filter

class-gravity-flow.php, css/entry-detail.css, css/feed-list.css, css/form-settings.css, css/frontend.css, css/inbox.css, includes/pages/class-inbox.php, js/feed-list.js, js/frontend.js
Ready for an initial code review for the Step Highlight - Color Setting.
- All step types get new setting 'Highlight - Highlight this step' that is not selected by default.
- Part 1 PR has step_highlight_type hidden / defaulted to color
- New JS dependency to wp-color-picker on step edit screen
- New filter - gravityflow_step_highlight_color_inbox - that could be used to change from a step-defined color to a field-derived status/priority. Passes $form['id'], $entry as additional parameters to the step_highlight_color to return (color hexcode)
Defined step highlight color can display in 3 locations:
1. Inbox Shortcode - new column step_highlight - off by default as true/false
1. Workflow inbox - on by default args, can be overridden through gravityflow_inbox_args
1. Workflow Step List
PR …
=> Step Highlight

class-gravity-flow.php
When the inbox shortcode is used, the success notice HTML markup isn't wrapped in any GravityFlow identifying markup (like `gravityflow_workflow_wrap` which occurs after the notice). This PR makes it easier to target the GravityFlow success notice directly.
The error notice wasn't modified because it has a unique GravityFlow class (`gravityflow_validation_error`) already.
=> Add a unique GravityFlow class to the update notice is it can be targeted via CSS

includes/pages/class-entry-editor.php
Section Breaks show during the User Input step regardless of being selected in the UI. This change adds to ce3e767f937f02dfb0648269a02b2caea12c7805 to account for the Selected Fields option being enabled.
=> Fix conditional logic issue with section breaks when the Selected Fields display mode is enabled

class-gravity-flow.php
This filter will allows developers to hide custom fields from the Display Fields setting. A working example can be found here: https://github.com/GravityPDF/gravity-pdf-previewer/pull/33/files
=> Allow the Display Fields list to be filtered

class-gravity-flow.php
On the Entry Detail screen workflow info box, the Last Updated and Submitted dates were being passed through GFCommon::format_date with a hard-coded 'Y/m/d' date_format parameter. This PR adds a new filter - gravityflow_date_format_entry_detail - to that parameter.
Note for translation / review...The impact is only displayed out of GFCommon::format_date for timestamps older than 24 hours (getting escaped through '%1$s at %2$s') instead of '%s ago'
=> 4933 translation filter

change_log.txt, class-gravity-flow.php
re: [HS#5186](https://secure.helpscout.net/conversation/506497512/5186?folderId=1113535)
Fixes an issue where conditional logic evaluation whilst getting the next step was using the old entry from before the update entry step had run.
=> Refresh the entry before getting the next step

includes/steps/class-step.php
This gist -  https://gist.github.com/Idealien/55cd37f96936637f5838f7267d7bde4a - would delay a non-business-hours step by 4 hours. 
**To Test:**
- Create a step that is scheduled in any format, easiest to test is 1 minute delay
- Add the gist above with appropriate check for step / form involved.
- Test at various times, or change server settings to cover appropriate cycles
Relates to HS#5309
=> Add new filter gravityflow_step_schedule_timestamp

change_log.txt, css/discussion-field.css, css/entry-detail.css, includes/fields/class-field-discussion.php, includes/pages/class-print-entries.php, js/entry-detail.js
Display more now applies by default on inbox (both edit and display felds) as well as status page.
**Form configuration:**
Add two Discussion type fields
Configure a Workflow user input step with save progress active
Configure an Approval step with the discussion field displayed
**Testing:**
Submit the form.
Access the inbox and save several discussion comments to trigger view more.
(Alternatively consider gravityflow_discussion_items_display_limit to set lower display)
Access the status page and note that view more is now accessible
Access print by browser File menu and GFlow button and note the full list still displays
=> 5406 discussion display more

change_log.txt, includes/models/class-activity.php, includes/pages/class-activity.php
**To Test:**
Add filter to gravityflow_limit_activity_events which returns int value 25
Notice that the Activity page (wp-admin/admin.php?page=gravityflow-activity) returns 25 results.
=> Adding filter gravityflow_limit_activity_events

change_log.txt, class-gravity-flow.php, gravityflow.php, includes/integrations/class-gp-nested-forms.php, includes/integrations/index.php
cc @spivurno
This enables the Nested Form field to function on the workflow detail page when selected as an editable field on the user input step.
**Child form configuration:**
- Add an Email type field.
- Configure a feed for an add-on such as MailChimp or User Registration.
- Configure a Workflow with two steps: approval step and then a step for the feed based add-on.
**Parent form configuration:**
- Add a Nested Form field selecting the above child form.
- Add one or more additional fields of any type.
- Configure a Workflow with two user input steps. The Nested Form field should be selected as editable on the first step. On the second step select one of the other fields as the editable field and the Nested form field as the display field.
**Testing:**
- Ensure logging is enabled for …
=> Add support for GP Nested Forms

includes/assignees/class-assignee.php, includes/steps/class-step.php
The assignee refactor knocked out the merge tags for the approval step. This PR ensures that all registered merge tags are replaced.
- Create an approval step with an approve link merge tag in an assignee email
- Submit a form to trigger the step.
- Verify that the merge tag is replaced by an empty string.
- Apply this PR, repeat the submission and check the merge tag is replaced properly.
=> Fix merge tags for approval step

includes/steps/class-step-feed-add-on.php
Fixes an issue with the status evaluation of feed add-on based steps with feeds using conditional logic.
Configure a form with two feeds for a feed based add-on such as MailChimp. The second feed should have a conditional logic rule which will not be met.
Configure a workflow with a feed based step, with both feeds selected, followed by an approval step.
Testing with the master branch you'll find the following:
- the feed add-on step starts with a status of pending
- the first feed is processed
- the second feed is not processed as the logic is not met
- the step status remains pending
- the approval step does not start
Testing with this branch you'll find the following:
- the feed add-on step starts with a status of pending
- the first feed is processed
- the …
=> Fixed incomplete step when feed logic not met

includes/pages/class-entry-editor.php
re: [HS#5627](https://secure.helpscout.net/conversation/544754262/5627?folderId=1113535)
Fixes an issue where the post category field is not populated with the entry value on the user input step.
Import the form from [this note](https://secure.helpscout.net/conversation/544754262/5627?folderId=1113535#thread-1484907570) on the ticket.
Complete the form selecting one or more categories.
View the entry in the workflow inbox.
Testing with the master branch you will find the field is not populated with the entry value.
Testing with this branch you should find the field is now populated.
=> Fixed editable post category field value

change_log.txt, includes/steps/class-step-approval.php
***Test  Instructions***
* Create an approval step with more than 2 assignees and approval policy set to 'all'
* Add [this gist](https://gist.github.com/Idealien/8c97b322370b0252ded58d5932f6b050) to your functions.php
* Update the step ID in filter to match your test step
* Test various approval scenarios
The gist is set so that any 2 approvals will complete the step, with any rejection continuing to reject the entire step. Other use cases could apply much different logic such as % of approve/reject with minimum number of non-pending responses.
=> Added gravityflow_step_status_evaluation_approval

includes/pages/class-entry-editor.php, includes/steps/class-step-user-input.php
Fixes an issue where the post image field is not populated with the entry value on the user input step.
- Create a form with a post title, body, and image field. Enable display of the title, caption, and description on the post image field.
- Create a user input step with the post image field as the editable field.
- Submit the form completing all three post fields.
With master: View the entry in the workflow inbox and find the post image field is empty.
With this branch: 
- View the entry in the workflow inbox and find the post image field contains the existing file, title, caption, and description.
- Change the title and submit the step. On the entry detail find the file, caption, and description remain the same and the title has been updated. Check the media …
=> Fixed editable post image field value

change_log.txt, includes/fields/class-field-discussion.php
re: [HS#5695](https://secure.helpscout.net/conversation/551945900/5695?folderId=1113535)
Fixes a PHP warning for the Discussion field hidden items with PHP 7.2.
=> Fixed PHP warning

change_log.txt, includes/pages/class-status.php
***Test Instructions***
- Use master branch and go to status page
- Note that status column for pending entries includes the duration since step was started
- Perform export and note that status column for pending entries only includes the status.
- Switch to branch 5436-status-export-pending
- Note that both status table and export contain the duration (export has it as separate column)
=> Revise export  to output pending status with duration

includes/steps/class-step-user-input.php
re: [HS#5627](https://secure.helpscout.net/conversation/544754262/5627?folderId=1113535)
Fixes an issue where the original image would be retained on save if there had been a validation error in another field.
See the ticket for testing instructions.
=> Fixes saved post image value following validation error

includes/assignees/class-assignees.php, includes/class-api.php, includes/steps/class-step.php
Fixes [HS5571](https://secure.helpscout.net/conversation/539669601/5571?folderId=1113498).
Entries can get stuck in the inbox of assignees even when removed. The PR purges all assignees when a step or workflow is restarted or cancelled.
Master:
- Add a user field to a form and assign a step to it.
- Submit the form then change the user in the Gravity Forms entry edit page.
- Restart the step from the admin actions
- The old assignee still sees the entry in the inbox.
This branch:
- Restart the step and check the old assignee no longer sees the entry in the inbox.
- Check the same with workflow restart and cancel.
- Ensure there are no side effects with the SQL like deleting meta that shouldn't be deleted
- Ensure it works on both Gravity Forms 2.2 and 2.3.
=> Fix assignees after restart

includes/pages/class-status.php
Fixes [HS5740](https://secure.helpscout.net/conversation/555460464/5740/?folderId=1113492).
This PR fixes an issue where the status shortcode is only responsive when using an English translation. This is because the styles target the table classes with 'entries' e.g. table.wp-list-table.entries. 'entries' is currently translated so making it not translated in this context fixes the issue.
On master
- Switch to Spanish, Italian or any or supported language
- Check the status shortcode is not responsive
On this branch
- Check the status shortcode is responsive and check there are no other side effects of this fix.
=> Fix responsive status shortcode for translations

includes/assignees/class-assignee.php, includes/class-common.php, includes/merge-tags/class-merge-tag-assignee-base.php, includes/merge-tags/class-merge-tag-workflow-approve-token.php, includes/merge-tags/class-merge-tag-workflow-approve.php, includes/merge-tags/class-merge-tag-workflow-cancel.php, includes/merge-tags/class-merge-tag-workflow-reject-token.php, includes/merge-tags/class-merge-tag-workflow-reject.php, includes/merge-tags/class-merge-tag-workflow-url.php, includes/steps/class-step-approval.php, includes/steps/class-step.php
re: [HS#5737](https://secure.helpscout.net/conversation/555366910/5737?folderId=1113535)
Fixes an issue where the created_by merge tag is being replaced in `Gravity_Flow_Assignee` when the entry is not passed in the `Gravity_Flow_Merge_Tags` initialization arguments.
Merge tags which extend `Gravity_Flow_Merge_Tag_Assignee_Base` will be replaced when processing is triggered in `Gravity_Flow_Assignee` while all other merge tags will be replaced when `GFCommon::send_notification` triggers merge tag processing. This also ensures merge tags such as workflow_fields are only replaced after the gform_notification filter has been used to change the message format from html to text.
=> Fix merge tag replacement timing

includes/merge-tags/class-merge-tag-workflow-approve.php, includes/merge-tags/class-merge-tag-workflow-reject.php
The one-click actions (approve and reject) from emails weren't working anymore because the tokens were created without an action. This PR fixed that.
=> Fix one-click actions

class-gravity-flow.php
This PR fixes a performance issue which can affect sites with a lot of users. The list of users is currently generated on every admin request. The WordPress function `get_users()` performs one query for every user meaning that a site with 1000 users will generate 1000 unnecessary requests on every admin page load. This PR generates the list only on the settings page.
Fixes [HS5993](https://secure.helpscout.net/conversation/578178309/5993/?folderId=516731)
=> Load users only when needed

includes/steps/class-step.php
This PR fixes an issue with the Multi-User field on the User Input step where no fields are editable for the assignee.
To reproduce the issue on master
- Add a Multi-User field to a form.
- Assign a User Input step to the Multi-User field and configure some editable fields.
- Select some users in the Multi-User field and submit the form.
- Check the inbox and verify that the editable fields are not editable.
On this branch, the editable fields will be editable.
=> Fix multi-user editable fields

includes/assignees/class-assignee.php
re: [HS#5910](https://secure.helpscout.net/conversation/571956500/5910/?folderId=1113492)
Fixes a fatal error which can occur when the current users permissions are checked on the entry detail page and the user is accessing the page anonymously using `{workflow_entry_url: page_id=n}` in a form notification, sent before the workflow starts, pointing to a page containing `[gravityflow page="status" allow_anonymous="true"]`
=> Fixed assignee fatal error

change_log.txt, class-gravity-flow.php
re: [HS6059](https://secure.helpscout.net/conversation/584040952/6059?folderId=1113417)
Fix a notice originating from the latest version of GravityView where some filters don't have keys.
=> Check the filter has a key

change_log.txt, includes/pages/class-inbox.php, includes/pages/class-status.php
Refer to #6067 for specific request scenario.
An example snippet which uses the new filters to prevent entries of a specific form from being shown to inbox / status. 
```
add_filter( 'gravityflow_form_ids_status', 'shortcode_display_args_control', 10, 2 );
add_filter( 'gravityflow_form_ids_inbox', 'shortcode_display_args_control', 10, 2 );
function shortcode_display_args_control( $form_ids, $search_criteria ) {
$workflow_form_ids = gravity_flow()->get_workflow_form_ids();	
unset( $workflow_form_ids[ array_search( '3', $workflow_form_ids ) ] );
return $workflow_form_ids;
}
```
Do you think additional parameters be added?
Something that might help to differentiate between admin view or shortcode view perhaps?
=> Creation of 2 filters to control form(s) used in GFAPI searches for inbox and status tables

includes/pages/class-entry-editor.php
In some situations (like with GP Nested Forms), the gform_pre_render may be called multiple times in a single page load. Currently, Gravity Flow will filter all forms that are filtered through gform_pre_render when editing an entry.
=> Updates filter_gform_pre_render() method to only apply to current form.

change_log.txt, class-gravity-flow.php, includes/class-api.php
re: [HS#6233](https://secure.helpscout.net/conversation/605682690/6233?folderId=1113492)
Added the "Workflow: cancelled" choice to the event setting on the Gravity Forms edit notification page. Notifications assigned to this event will be sent at the end of the cancellation process.
=> Added workflow cancelled notification event

class-gravity-flow.php
This PR adds checks to make sure that the form and steps are active before processing reminders and queued entries.
Fixes [HS6291](https://secure.helpscout.net/mailbox/d945f27d1fa1b0fa/516732/) and [HS6213](https://secure.helpscout.net/conversation/602009892/6213/?folderId=516731)
To reproduce, set up assignee email reminders for a step, deactivate the step and the reminder email will still be sent out. The issue will remain even if the form is deactivated.
On this branch, the emails will not be sent out for entries on deactivated steps or forms and queued entries will not start.
=> Check forms and steps are active before processing entries

change_log.txt, includes/fields/class-field-assignee-select.php, includes/fields/class-field-multi-user.php, includes/fields/class-field-user.php
A resolution to https://github.com/gravityflow/gravityflowformconnector/pull/6 which is now closed.
The form export attached has two forms that validate the form connector assignment by field works for the GFlow field types (assignee - by user, role, user, role and multi-user). They all also work for export. PR also passes all unit and acceptance tests currently.
[gravityforms-export-2018-07-01.json.zip](https://github.com/gravityflow/gravityflow/files/2153269/gravityforms-export-2018-07-01.json.zip)
Adding Steven and Richard for review
=> HS#5583 - Re-factor get_value_export for multiple user field types

change_log.txt, includes/fields/class-field-discussion.php
**Prior to this PR:**
- Discussion show/hide toggle would show on any page scenario where field values were output except for the form editor or cases where gravityflow_discussion_items_display_toggle was set to false.
- The JS to provide show/hide functionality would only occur on Gravity Flow pages, resulting fully hidden discussion items when being displayed in other contexts.
PR resolves this issue by ensuring show/hide toggle only displays on Gravity Flow pages.
**Testing**
- Data - Create entry with discussion field and > 10 comments to it.
- Positive - Continue to see show/hide on inbox and status entry detail views
- Negative - Display field value through a separate plugin (GView or generated posts as example) does not have show/hide toggle.
**Documentation**
Upon version …
=> Discussion display toggle

change_log.txt, includes/fields/class-field-multi-user.php
This PR fixes an issue with the Multiuser field where the user IDs are displayed instead of the names on the entry detail page and the workflow entry detail page.
=> Fix display on entry detail pages

change_log.txt, class-gravity-flow.php
Adds "Authorized" as an available choice for the entry Payment Status property in the step condition setting.
=> Add authorized choice to feed logic

change_log.txt, includes/pages/class-inbox.php
Refer to [HS 6570](https://secure.helpscout.net/conversation/640747773/6570?folderId=1113497) for details.
**To replicate issue:**
* Create form with an upload field set for single upload and a workflow step assigned to user
* Create entry
* Create page with the inbox shortcode with form / fields attributes to display
[gravityflow page="inbox" form="1" fields="2,3"]
* Receive error FATAL ERROR: UNCAUGHT ERROR: CLASS 'GFENTRYLIST' NOT FOUND IN .../WP-CONTENT/PLUGINS/GRAVITYFORMS/INCLUDES/FIELDS/CLASS-GF-FIELD-FILEUPLOAD.PHP ON LINE 449
**Analysis/Resolution:**
The UI issue is that GForms is trying to call GFEntryList::get_icon_url to display the upload icon and on GFlow side the GFEntryList is not instantiated to support it. Resolution is consistent with other requires to GForms …
=> Inbox Page - File Field Column

class-gravity-flow.php
With Gravity Forms 2.4 and greater the payment status choices in the step condition UI will be populated by `GFCommon::get_entry_payment_statuses_as_choices()` which makes the new `gform_payment_statuses` filter available for defining additional payment statuses.
=> Update to use GFCommon::get_entry_payment_statuses_as_choices() with GF2.4

change_log.txt, includes/pages/class-inbox.php
See HS#6681
This PR adds the filter gravityflow_columns_inbox_table to enable customization of columns on the inbox or shortcode display of inbox. It brings parity to the status page of the shortcode with [gravityflow_columns_status_table](https://docs.gravityflow.io/article/161-gravityflowcolumnsstatustable) filter.
An example usage to remove a default column and add a custom column would be:
```
add_filter( 'gravityflow_columns_inbox_table', 'custom_inbox_column_titles', 10, 2 );
function custom_inbox_column_titles( $columns, $args ) {
unset( $columns['created_by'] );
$columns['assignees'] = 'Assignee(s)';
return $columns;
}
```
FYI - The associated filter to display a custom column value would be 
```
add_filter( 'gform_entries_field_value', 'custom_column_assignees_field_values', 10, …
```
=> Added filter to allow inbox columns to be adjusted

includes/pages/class-inbox.php, includes/pages/class-status.php
Updates the inbox and status pages to use `GFCommon::get_entry_payment_status_text()` with Gravity Forms 2.4 and greater when getting the payment status to be displayed in the column. This change adds support for custom and translatable payment statuses.
Also refactors the status page column methods to reduce duplication around getting the entry url and gravityflow_field_value_status_table filter.
```
add_filter( 'gettext', function ( $translated_text, $text, $domain ) {
if ( $domain === 'gravityforms' && $text === 'Authorized' ) {
$translated_text = "Authy'd";
}
return $translated_text;
}, 10, 3 );
add_filter( 'gravityflow_inbox_args', function ( $args ) {
$args['form_id'] = 8;
$args['field_ids'] = array( 'payment_status' );
return $args;
} );
add_filter( 'gravityflow_status_args', …
```
=> Update inbox and status page payment status column support

class-gravity-flow.php, includes/merge-tags/class-merge-tag-workflow-url.php
This PR allows tokens to be used inside the Gravity Forms confirmations by processing the workflow before the confirmation is handled. It also adds the assignee attribute to the workflow URL merge tags which takes the assignee key. This is useful for displaying email assignees a workflow link inside the confirmation. e.g. {workflow_entry_link: assignee=email_field|3}
- This requires Gravity Forms 2.3.3.10 which contains the gform_pre_handle_confirmation action.
- Add the assignee attribute to a workflow URL merge tag in a Gravity Forms confirmation e.g. {workflow_entry_link: assignee=email_field|3}
- Ensure that the link works as expected.
- Remove the assignee attribute and submit while logged in as the assignee of the first step. The token="true" attribute must …
=> Add support for tokens in the confirmation

change_log.txt, css/frontend.css
This PR fixes RTL CSS styles issue in Divi and other themes that force table cells to be `text-align: left;`.
See the screenshot for the result of the inbox page in a Divi theme:
See the screenshot for the result of the entry detail page in a Divi theme:
=> Fix RTL CSS in the entry detail page for Divi and other themes

class-gravity-flow.php, gravityflow.php, includes/EDD_SL_Plugin_Updater.php, includes/class-extension.php, includes/class-feed-extension.php
This PR update the EDD SL Class to the latest version and adds some fixes. The EDD item name is now deprecated in  favour of the item ID. It also adds admin notices for invalid extension licenses, fixes admin notices on multisite and ensures that the admin notices are not displayed while the installation wizard is being displayed on single site.
- Ensure the admin notices for Gravity Flow and extensions are only displayed on the main site.
- Ensure there are no regression issues for single site.
- Ensure the admin notices are not displayed while the installation wizard is being displayed.
=> Update edd sl class

includes/steps/class-step-user-input.php
re: [HS#6863](https://secure.helpscout.net/conversation/673021181/6863?folderId=1113495)
Fixes an issue where the "Workflow: user input" notification event is triggered before the entry has been updated which results in stale data being used when notification routing/conditional logic is evaluated and when merge tags in the notification settings are processed.
=> Trigger user input notification event after entry save instead of before

class-gravity-flow.php
This PR triggers the workflow using the gform_entry_pre_handle_confirmation filter added in Gravity Forms 2.3.4.2 so the merge tags and confirmation can use the updated entry.
Fixes [HS#6851](https://secure.helpscout.net/conversation/671087176/6851?folderId=516732)
- Create a form with an email field and two text fields.
- Add a webhook step to update one of the text fields e.g. the translation example
- Add a Form Submission step with a condition based on the value in a field changed by the webhook
- Add another Form Submission step without a condition as a catchall
- Set the confirmation redirect to `{workflow_form_submission_url: assignee=email_field|3}` where 3 is the ID of the email field.
- Submit the form while logged out to ensure the email toke is working …
=> Trigger the workflow on gform_entry_pre_handle_confirmation

includes/assignees/class-assignee.php, includes/merge-tags/class-merge-tag-assignee-base.php, includes/merge-tags/class-merge-tag-workflow-approve-token.php, includes/merge-tags/class-merge-tag-workflow-approve.php, includes/merge-tags/class-merge-tag-workflow-cancel.php, includes/merge-tags/class-merge-tag-workflow-reject-token.php, includes/merge-tags/class-merge-tag-workflow-reject.php, includes/merge-tags/class-merge-tag-workflow-url.php, includes/merge-tags/class-merge-tag.php, includes/steps/class-step-feed-twilio.php
This PR does the following:
1. Adds the step merge tag attribute to allow merge tags to specify the step for which tokens must be generated. This allows feed add-ons to specify the step. For example, a Twilio or Slack message can contain a one-click approval link for the next step.
2. Fixes an edge case where the assignee attribute will remove the assignee added in the constructor and override the assignee in subsequent instances of the merge tag.
3. Fixes an issue with the current version of the Twilio Add-On where URLs get encoded breaking parameters. There's another issue with the shortener - currently, the URL Shortener in the Twilio Add-On will break links with more than one parameter. This is addressed in the Twilio Add-On repo PR5.
Fixes …
=> Add the step merge tag attribute

change_log.txt, includes/steps/class-step.php, tests/unit-tests/test-step-expiration.php, tests/unit-tests/test-step-schedule.php
Fixed a typo for the step expiration_date_field_offset property which caused a "A non-numeric value encountered" warning with PHP 7.1 and an incorrect expiration timestamp to be returned with earlier PHP versions.
Unit tests included.
=> Fix expiration timestamp and evaluation for date field and weeks offset

includes/steps/class-common-step-settings.php, includes/steps/class-step.php
Resolve a fatal error when Gravity PDF is activated, but the system requirements aren't met, and a Gravity Flow step is loaded.
=> Ensure the PDF methods exist before trying to use it

includes/steps/class-step.php, tests/unit-tests/test-step-expiration.php, tests/unit-tests/test-step-schedule.php
re: [HS#6997](https://secure.helpscout.net/conversation/686774876/6997/?folderId=1113492)
Added the gravityflow_step_expiration_timestamp filter.
```
add_filter( 'gravityflow_step_expiration_timestamp', function( $expiration_timestamp, $expiration_type, $step ) {
// Modify the timestamp.
return $expiration_timestamp;
}, 10, 3 );
```
Also refactored the methods for getting the step schedule and expiration timestamps to reduce duplication.
=> Add expiration timestamp filter

change_log.txt, includes/steps/class-step-user-input.php
Currently when a user input step is saving progress the required field validation is performed in addition to any custom validations. The expectation is that saving progress shouldn’t trigger the required fields validation.
1. Setup form with multiple administrative fields as required
1. Add a workflow user input step with one of the Save Progress options enabled.
1. Submit the form and note that on attempt to save progress the required fields are....required.
1. Switch to user-input-save-validation branch and repeat step 3. Note that required fields are...not required.
1. Attempt to complete the user input step and note that required fields are...required.
=> User Input Step - Only check for required fields on step complete

includes/pages/class-entry-detail.php
re: [HS#7132](https://secure.helpscout.net/conversation/703413457/7132/)
Enables the GP eCommerce Fields Add-On to filter the order summary markup moving the discount and tax fields from the main body of the table down in to the footer.
Before:
After:
=> Add the gform_order_summary filter

class-gravity-flow.php, includes/steps/class-step.php
Added settings for the Email Service, default From Name, and default From Email. 
The From Email setting defaults to a text type setting unless Postmark is the selected service in which case it will change to a drop down populated with email addresses from the Postmark account.
If Mailgun is the selected service the email address domain will be validated on save.
Also reordered the app settings so the email and page settings are located before the published forms settings.
Updated `Gravity_Flow_Step::get_notification()` to use the new settings.
=> Added email related app settings

class-gravity-flow.php, includes/pages/class-entry-editor.php, includes/steps/class-step-user-input.php
This PR adds support to the User Input step for Repeater fields (added in Gravity Forms 2.4) editable fields. It also batches multiple field updates into single queries to improve performance - this bumps the minimum version Gravity Forms requirement 2.3.
**Testing in instructions**
- Ensure the Repeater field works as expected as display and editable fields on Gravity Forms 2.4.
- Check that no regression issues are introduced when using Gravity Forms 2.3.
=> Add support for Repeater fields

class-gravity-flow.php
This PR adds the entry filter setting which renders the Gravity Forms entry filter UI. The form_id setting property is mandatory. The filter_text property is optional but it must include a placeholder for the any/all drop down e.g. "Match {0} of the following criteria".
It supports multiple instances on the same step.
Add a step setting of type entry_filter. Set the values and save to ensure the settings are saved. Add another setting of the same type and ensure the value are saved correctly.
Test with the [Update Fields step PR](https://github.com/gravityflow/gravityflowformconnector/pull/19) in the Form Connector.
=> Add the entry filter step setting

class-gravity-flow.php
This PR adds the `<p>` tag to the admin screen feedback when it's missing in the original message.
=> Fix admin notice style

includes/integrations/class-gp-nested-forms.php
re: [HS#7326](https://secure.helpscout.net/conversation/722768570/7326?folderId=1113535)
Moves the gravityflow_is_delayed_pre_process_workflow filter so workflows for child entries can be delayed when the nested form field is included in the original submission and the field is set to process feeds on parent form submission.
=> Fix gp nested forms child workflows not being delayed

change_log.txt, class-gravity-flow.php
Refer to HS 7547
This PR resolves an issue where conditional routing with a multi-user field could lead to incorrect number of assignees being set for a step. The default GForms value match for 'contains' logic type would return true for potential route of selected User ID of 1 with a multiuser field containing selection of user ID 10.
- Create a form with a multiuser field
- Ensure your site has 10+ users
- Create an approval step with conditional routing for soft matching user IDs (2 & 22, 7 & 57, etc)
- Submit the form and select the larger user ID by name
- Verify that the step has been assigned to more users than is expected
- Switch to the PR branch and restart the step
- Verify that only the expected users have been set as assignee
=> Add filter to gform_is_value_match for multiuser field values

change_log.txt, includes/pages/class-inbox.php
re: [HS#7586](https://secure.helpscout.net/conversation/748963379/7586?folderId=1113535)
Fixes an issue where the inbox page excess entries indicator continues to display the limit as 150 when the page size has been changed using the gravityflow_inbox_paging filter.
- Without the filter check that the Gravity Flow default limit of 150 is displayed
- Add the filter setting a custom limit and then check that the limit is updated on the inbox page
```
add_filter( 'gravityflow_inbox_paging', function() {
return array( 'offset' => 0, 'page_size' => 30 );
} ); 
```
- Add the filter without the page_size arg and then check that a limit of 20 is displayed which matches the default page size used by GFAPI::get_entries()
```
add_filter( 'gravityflow_inbox_paging', function() {
return array( …
```
=> Fix inbox excess entries page size limit

change_log.txt, class-gravity-flow.php, includes/class-gravityview-detail-link.php, includes/pages/class-entry-detail.php
This PR enables a back link to be added to the entry detail screen to return user to the inbox/status page based on shortcode. 
- **back_link** - Default is false. Set to true to show the back link on entry detail page
- **back_link_text** - Default is 'Return to list'. Set a custom message per shortcode.
- **back_link_url** - Default is null. Enable non-GF shortcode pages to set a return link to their summary view.
- **gravityflow_back_link_url_entry_detail** - To allow customization of the link via code. The shortcode $args are passed as the 2nd argument allowing devs to control which scenarios they may want to customize.
- Updates the Gravity View integration of workflow_detail_link field. If the default GFlow inbox/shortcode page has the back_link=true attribute to its' shortcode, the …
=> Add back link to shortcode

change_log.txt, includes/pages/class-status.php
(Re-submit of PR #198 based off develop branch)
Refer to HS# 7384 and #7455
Add gravityflow_search_criteria_status filter to allow multi-field search criteria to be executed on the status page. Note that in order for it to filter the GFAPI get_entries request, the gravityflow_form_ids_status filter (or UI selection of matching form) must be used to define a single form id.
Example Code to trigger the filter to apply only on a front-end page /status/:
```
add_filter( 'gravityflow_search_criteria_status', 'status_search_criteria_control', 10, 1);
function status_search_criteria_control( $criteria ) {
if( false !== strpos( $_SERVER['REQUEST_URI'], '/status/' ) ) {
$criteria['field_filters']['mode'] = 'any';
$criteria['field_filters'][] = array(
'key'     => '5',
'operator' => 'is',
'value' …
```
=> Search criteria

change_log.txt, includes/class-api.php, includes/class-common.php, includes/merge-tags/class-merge-tag-workflow-note.php, includes/merge-tags/class-merge-tag-workflow-timeline.php, includes/merge-tags/class-merge-tags.php
See HS#7892
A call to $api->get_timeline results in an undefined method error.
This PR resolves that issue by bringing functions from Gravity_Flow_Merge_Tag_Workflow_Timeline up to Gravity_Flow_Common to enable the api call to use them as well.
**To Test:**
* Add the following to a theme template page or other appropriate location.
* Modify form ID / entry ID to match your test environment
* Run with master branch and receive an undefined method error
* Switch to 7892-get-timeline branch and note that error is resolved.
```
$form_id = 11;
$entry_id = 14;
$entry = GFAPI::get_entry( $entry_id );
$api = new Gravity_Flow_API( $form_id );
$timeline = $api->get_timeline( $entry );
echo '<h1>API Timeline</h1>' . str_replace( "\n", "<br/>", $timeline );
$merge_tag = GFCommon::replace_variables( …
```
=> Fix issue with GFlow API get_timeline

class-gravity-flow.php, includes/class-extension.php, includes/class-feed-extension.php
Ensures that only one license check is made on each request. Also excludes third-party extensions from the admin notices.
=> Add license check throttling

includes/wizard/class-installation-wizard.php
The WP styles have knocked out the styles of the installation wizard. This a temporary fix until we can find a better solution.
To reproduce the issue add `&gravityflow_installation_wizard` to the end of any Gravity Flow page.
=> Fix wizard styles

class-gravity-flow.php, includes/class-extension.php, includes/class-feed-extension.php, includes/wizard/class-installation-wizard.php, includes/wizard/steps/class-iw-step-license-key.php
1. Activate the site if the constant is set for core and extensions.
2. Hide the license key settings for extensions if the license key constant is set.
3. Hide the settings tab for extensions if there are no settings on the tab.
4. HIde the license key step if the constant is defined.
Test with the following PRs:
https://github.com/gravityflow/gravityflowchecklists/pull/16
https://github.com/gravityflow/gravityflowflowchart/pull/3
https://github.com/gravityflow/gravityflowpdf/pull/7
=> Add extension license key constant

includes/class-oauth1-client.php, includes/steps/class-step-webhook.php
Fixes an issue where the signature for GET requests are not generated corrected when the URL has query params.
1. Add a connected app of type Gravity Forms OAuth1.
2. Add a webhook step using a GET request with a query string e.g.
=> Fix OAuth1.0a GET auth

class-gravity-flow.php
This PR resolves an issue where the Gravity Flow import message appears upon importing a form when the form object contains the `gravityflow` feeds array but does not have any feeds.
1. Export two forms, separately, while running Gravity Flow: One with a Gravity Flow feed, one without
1. On `master` branch, import the form with a feed. The import message should appear.
1. On `master` branch, import the form without a feed. The import message should appear.
1. On `fix-import-message` branch, import the form with a feed. The import message should appear.
1. On `fix-import-message` branch, import the form without a feed. The import message should not appear.
=> Fix import message showing when form has no feeds

includes/integrations/class-gp-nested-forms.php
re: [HS#7446](https://secure.helpscout.net/conversation/734794694/7446?folderId=1113535#thread-2100372024)
Delays triggering the workflow for child submissions by switching from the gform_entry_created hook to the gform_after_submission hook. This resolves a timing issue where the workflow was being triggered before perks such as Nested Forms and Unique ID have updated the child entry on the gform_entry_created (NF) and gform_entry_post_save (UID) hooks.
Test forms and instructions in the ticket note from Subrato
=> Delay triggering child workflow on parent submission until after perks have updated the entry

change_log_temp.txt, class-gravity-flow.php
Refer to HS#7755
**Issue** 
Provide method for customisation of the next step a workflow will process. Example scenario is  a successfully completed user input step needs to restart the same step in order to trigger different assignee's (based on value changes of current step)
**Closest Alternatives**
- gravityflow_post_process_workflow is too late in workflow cycle to trigger change
- gravityflow_step_complete would allow the GFlow $api->restart_step to modify $entry meta to indicate a successful restart, however it would require use of a custom event (via wp_schedule_single_event) and still not prevent the next ordered workflow step or notification from starting. An additional refresh of the entry during process_workflow does not modify the active step / next step logic enough for this …
=> Add filter gravityflow_next_step

change_log.txt, class-gravity-flow.php
See [8206](https://secure.helpscout.net/conversation/788830995/8206?folderId=1776095)
This PR resolves an issue with conditional routing for step assignees involving date fields which were not being correctly evaluated and would return false in many cases they should not.
- Create a form with a date field
- Create a step which uses conditional routing and the date field for condition (all operators supported)
- Verify the expected assignee is assigned to the step.
- While the field format is yyyy-mm-dd through the use of strtotime for evaluation the majority of date formats which users might input into the routing field will also evaluate correctly.
This PR also renames the function hooked to gform_is_value_match (to filter_gform_is_value_match) to allow more …
=> Fix date-field based conditional routing

includes/steps/class-step-feed-constantcontact.php
This PR adds support for the Gravity Forms Constant Contact add-on.
1. Setup a Constant Contact feed.
2. Add a Constant Contact step in your workflow. Better to put an Approval step before it.
3. Submit the form, make sure the contact only gets added AFTER the Approval step.
=> Add the new Constant Contact step

includes/steps/class-step-update-user.php
This PR fixes an issue reported in this ticket: [HS#8531](https://secure.helpscout.net/conversation/808963392/8531?folderId=2308452), that "Update User" workflow step does not seem to be updating roles.
To replicate the issue :
1. Import and publish the attached form.
2. Edit and assign the 'Approval' step to a user of your choice.
3. Configure the 'update user' step as shown here.
4. Submit the form and Approve the entry. The new role will not be added to the user.
With this PR, you'll have to update the "Update User" step to get the settings updated. Then restart the workflow or submit new entries, it would then work as expected.
=> Fix "roles" aren't added to users in the "Update User" step

change_log.txt, includes/steps/class-step-webhook.php
See [HS#8371](https://secure.helpscout.net/conversation/798625291/8371?folderId=1776095)
When the outgoing webhook step setting Request Body to Raw Request and merge tags were used within the body, any JSON reserved characters ( : " / tab, etc) would not be properly encoded and would not result in the expected data being sent.
Using a late hook to gform_merge_tag_filter this branch/PR ensures that any uses of merge tags have their values json_encoded prior to the webhook being sent.
- Create an outgoing webhook step with Request Body set to Raw and use {:1} or other merge tags in the body
- Submit a form that has JSON reserved characters in the field of merge tag use
- Capture the API outgoing value and [validate the JSON format](https://jsonlint.com/)
- Switch to …
=> Fix webhook raw merge tags

change_log.txt, includes/fields/class-field-assignee-select.php
See [HS #8602](https://secure.helpscout.net/conversation/813686335/8602?folderId=1776095)
**Issue:**
Assignee workflow field, adds a blank entry in the list of assignees (users, roles and fields) when a 'Placeholder' text is added. If this blank value is selected as assignee, the user with the alphabetical priority of 'Name' will be assigned.
**Steps to replicate the issue:**
- Create a form with an Assignee field and add a placeholder text under Appearance -> Placeholder.
- Add a 'User Input' workflow step. 
- Make the Assignee field editable and assign the step to yourself.
- Publish and Submit the form
- The Assignee field will include blank options as first in Users choice block, Roles choice block and Fields choice block.
- Checkout the fix-assignee-placeholder branch and reload the …
=> Resolve Assignee field type issue with extra choices due to placeholder setting

class-gravity-flow.php, includes/steps/class-step-update-user.php, includes/steps/class-step.php
This PR adds a multisite validation in the Update User step that before updating the user data, we check if the user is a member of the current site. Their data won't be updated if they are not members of the current site, and an entry note will be added to address it.
Also, we add a new method `get_required_capabilities()` in the `Gravity_Flow_Step` class. When saving step settings, we will check if the current user has all required capabilities. We then add a new required capability "edit_users" for the Update User step. So now users without the "edit_users" cap, can only view the step but will not be able to update the step.
We also add entry notes when the user cannot be found at all.
1. Testing form: [gravityforms-export-2019-03-30.json.zip](https://github.com/gravityflow/gravityflow/ …
=> Enhance the security of the Update User step

change_log.txt, includes/pages/class-inbox.php, includes/steps/class-step.php
**Issue:**
[gravityflow page="inbox" due_date="true"] would display current date for columns that did not have any due date settings defined.
Addresses [HS8792](https://secure.helpscout.net/conversation/823836949/8792/)
* Create a form with at least one step that does not have due date settings defined.
* Add [gravityflow page="inbox" due_date="true"] to a page
* See that the due date column shows current date
* Switch to fix-due-date-default branch
* See that entry w/o due date settings have blank value in due date column
=> Fix issue with inbox due date column displaying default date value

includes/steps/class-step.php
This PR fixes a PHP notice when evaluating conditional routing.
To reproduce, set up conditional routing to use any field as part of a condition. Submit an entry and open the entry in the workflow detail page.
=> Fix notice when evaluating conditional routing

includes/pages/class-inbox.php
This PR moves the step highlight logic into the same method as the other column values. This helps to separate the markup from the values for the PHP API and REST API.
Check the highlight works as expected in both the shortcode and admin. Check the overdue highlight works as expected with and without overriding the step highlight setting.
=> Allow highlight value to be returned like other column values

change_log.txt, class-gravity-flow.php
This PR adds missing echo parameter to 2 of the calls to settings_select during step settings definition which was causes the before/after and date-field selector to display twice. Appears to be introduced via #208.
=> Fix schedule date field settings

change_log.txt, includes/steps/class-step-feed-slicedinvoices.php
re:[HS#8805](https://secure.helpscout.net/conversation/824853488/8805?folderId=2308452)
This PR fixes an issue that a Sliced Invoices step cannot be released when the status is manually updated to Paid.
Currently we depend on the hook action `sliced_invoice_status_update` to release entries from a Sliced Invoices step. But it is only called when payments are made by the PayPal gateway, thus manually updating invoice status cannot trigger the workflow step at all.
1. Reproduce the issue based on the ticket notes.
2. Switch to this branch, the entries should be released as expected.
=> Release entries from a Sliced Invoices step when invoice status updated manually

change_log.txt, class-gravity-flow.php, includes/fields/class-field-assignee-select.php, includes/fields/class-field-multi-user.php, includes/fields/class-field-user.php
re:[HS#8901](https://secure.helpscout.net/conversation/831361590/8901/), [HS#8868](https://secure.helpscout.net/conversation/829212605/8868?folderId=2308452)
This PR fixes an issue introduced by PR #239 that form submissions with Assignee, User or Multi-User fields fail at validation.
When tracking down the issue we realized that if people set custom arguments for `get_users()`, without specifying the `fields` key in the array, the function returns user IDs as "integer," otherwise it returns them as "string," thus using "strict" check for `in_array()` comparison makes validation fail.
1. Create a form with Assignee, User and Multi-User fields.
2. Use the following legacy snippets to alter arguments for `get_users()`:
```
add_filter( 'gravityflow_get_users_args', …
```
=> Fix validation to Assignee, User and Multi-User fields

class-gravity-flow.php
This PR fixes an issue with the status shortcode where the `display_all` attribute is forced to `false` when the user can `gravityflow_status_view_all`. This occurs when the `allow_display_all_attribute` setting is not enabled in the security settings.
It also fixes a typo in the check for the status page attributes.
=> Fix display_all for users that can gravityflow_status_view_all

change_log.txt, includes/assignees/class-assignee.php
[See HS#8868](https://secure.helpscout.net/conversation/829212605/8868?folderId=1113492)
If a notification step has a multi-user field set as the assignee and entry contains multiple selections the current version will not deliver a notification to the multiple users selected.
**To Test**
* Create a form with one (or more multi-user workflow fields)
* Create a notification step with the multi-user fields as assignee
* Submit an entry and check email delivery (mailhog in local)
* Note that not all expected recipients received the notification
* Switch to fix-multiuser-field-notification branch and repeat notification step
* Receive all expected notifications
=> Fix Notification Step with multi-user field assignee(s)

class-gravity-flow.php, includes/pages/class-status.php
This PR adds support for multiple form IDs to be used in the status shortcode. e.g. [gravityflow page="status" form="1,2"]
It also adds support enqueuing scripts when the Gravity Flow blocks are added.
Check for regressions with no forms and with one form especially edge cases that use the filters. Then check that the status shortcode works as expected with multiple form IDs in the `form` attribute.
=> Add support form multiple forms in the status shortcode

class-gravity-flow.php, includes/pages/class-submit.php
This PR adds the `forms` shortcode attribute to the submit page to allow the forms to be filtered on the submit page. e.g. [gravityflow page="submit" forms="1,2,3"]
=> Add forms attribute to submit shortcode

change_log.txt, class-gravity-flow.php
See [HS#8851](https://secure.helpscout.net/conversation/827940711/8851?folderId=1776095).
Filter name gravityflow_assignee_eamil_reminder_repeat_days has typo (email).
This PR:
- Adds gravityflow_assignee_email_reminder_repeat_days (no typo)
- Updates doc block to note depreciated nature of gravityflow_assignee_eamil_reminder_repeat_days
=> Fix filter name gravityflow_assignee_eamil_reminder_repeat_days

change_log.txt, includes/steps/class-steps.php
This PR fixes a PHP notice when loading feed message with AJAX.
1. Add a few steps in a form.
2. Activate Gravity Flow PDF Generator extension, create a PDF feed. When loading the feed settings page, your debug tool should yield a PHP notice, as the screenshot shows.
=> Fix PHP notice when loading feed message with AJAX 

includes/pages/class-status.php
In rare circumstances, a step may be deleted for an entry. In this case a fatal error will occur on the status page. This PR prevents the fatal error and displays the ID of the missing step.
=> Fix fatal error on the status page if step is deleted

includes/pages/class-entry-detail.php
Re: [HS#9348](https://secure.helpscout.net/conversation/858975495/9348?folderId=1113498)
This PR fixes an issue where administrators can see ALL fields in the workflow entry detail page, even they are not assignees of the current step.
1. Test with the test form from Subrato in the ticket.
2. With the `master` branch, you'll see all fields when you're an admin; with this branch you can only see the display fields.
=> Don't show all fields to administrators in workflow entry detail page

change_log.txt, includes/pages/class-entry-detail.php
Refer to [HS#9207](https://secure.helpscout.net/conversation/851721997/9207?folderId=1776095#)
User Input steps cannot currently display the order summary without having a product field edit/display. The step settings already include option whether to display Order Summary.
This PR checks whether that is set as an additional reason to display the Order Summary.
See HS#9207 for test form/instructions.
=> Fix order summary on user input steps without product fields

includes/steps/class-step-feed-post-creation.php
re: [HS#9454](https://secure.helpscout.net/conversation/865456769/9454?folderId=1113535)
Updates the Post Creation step to skip feed processing if a post has already been created by the APC feed; fixes an issue where duplicate posts are created when the workflow or step is restarted.
- Create a form with an Advanced Post Creation feed
- Add a Post Creation step
- Submit form
- Go to the Posts page and find the post was created
- Go to the Status page and restart the workflow
- Go to the Posts page find a duplicate post was created
- Update to this branch
- Repeat test and find the duplicate post is not created
=> Skip APC processing when post already exists for feed

change_log.txt, css/entry-detail.css, includes/pages/class-entry-detail.php
Re: [HS#9416](https://secure.helpscout.net/conversation/862798240/9416?folderId=1776095)
This PR addresses a display issue with back links on entry detail page that prevented themes from customizing the spacing. It changes from using 2 line breaks following the $url built and filtered through gravityflow_back_link_url_entry_detail to a new div class - gravityflow-back-link-container - with a 2em bottom margin.
To test it change between master and this branch to see the markup differences with same visual result.
=> Change from line breaks to CSS for back link display

change_log.txt, includes/pages/class-entry-editor.php
Refer to [HS#9694](https://secure.helpscout.net/conversation/884090820/9694?folderId=1776095#)
*Issue:*
With the current version of gravity flow, when a numeric field has a 0 value and is selected for display (not edit) a blank value is being shown regardless of 'show empty field' selection.
*Resolution*
Change logic that numeric fields use to be based on rgblank GForms common function.
*Test instructions*
- Starting on the master branch
- Create a form with at least 1 number field and one other field type.
- Add a user input workflow step that keeps the number field as a display field (not edit).
- Submit an entry and specify 0 in the number field.
- Go to workflow inbox for the user input step.
- Verify that blank is shown for number field.
- Switch to this branch/PR and reload page
- …
=> Update user input step number field display with zero value

change_log.txt, includes/pages/class-entry-detail.php
See [HS#9727](https://secure.helpscout.net/conversation/884389675/9727?folderId=1776095) and [PHP 7.3 backward breaking change log](https://www.php.net/manual/en/migration73.incompatible.php).
"continue statements targeting switch control flow structures will now generate a warning"
The continue triggering warning is within the fields loop for entry detail display.
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in [local path]\gravityflow\includes\pages\class-entry-detail.php on line 932
**Steps to reproduce:**
- Run a version of PHP 7.3.X
- Set up a form with user input workflow with at least 1 display field and 1 editable field
- Access the workflow step with appropriate error logging or debugging active.
- See error message
- Switch to …
=> Fix PHP 7.3 warning due to continue

Dockerfile, change_log.txt, includes/steps/class-step-feed-zapier.php
re:[HS#9536](https://secure.helpscout.net/conversation/868343234/9536?folderId=1113497)
This PR fixes an issue that delayed Zapier steps send duplicate content from the first entry in queue, when there are multiple scheduled entries.
Please reproduce the error as the ticket described, and it will be fixed with this branch.
=> Fix delayed Zapier steps send duplicate content from the first entry in queue

change_log.txt, includes/steps/class-step-webhook.php
See [HS#10091](https://secure.helpscout.net/conversation/909527249/10091?folderId=1776095)
Adds the merge tag drop-down to the right side of raw body step setting for Outgoing Webhook, making it much easier to build the raw request with field and custom data values. It also increases the size of the raw body field to better support cases involving large/nested JSON structures.
**Steps to test**
- Create an outgoing webhook step
- Use the new merge tag dropdown
=> Outgoing Webhook - Add merge tag selector to raw body step setting

change_log.txt, includes/pages/class-status.php
See [HS#10496](https://secure.helpscout.net/conversation/931195708/10496?folderId=1776095)
This PR fixes an issue where the issue counts (All/Pending/Complete/Cancelled) would not have correct tallies if the gravityflow_form_ids_status filter was applied. It updates the order that status table prepare_items, views and filters are called as well as ensuring the class $total_count parameter is set earlier in logic for other functions to reference.
- Use the hooked filter below (updating for form IDs in your test environment.
- Note that the complete, pending, etc counts still show the values as if filter did not apply.
- Switch to this branch.
- Verify that the counts do match.
- Test with other column customizations.
```
add_filter( 'gravityflow_form_ids_status', …
```
=> Fix issue with counts in view bar not checking gravityflow_form_ids_status

change_log.txt, includes/pages/class-inbox.php
Refer to [HS#9627](https://secure.helpscout.net/conversation/877194159/9627?folderId=1776095)
The existing gravityflow_entry_link_inbox_table filter allows customization of the href tag (to add  target="_new" for example) but not to modify the URL which the links in inbox will send users to without adding parameters to it and/or repeating much of the display_entry_row function (violating D-R-Y principles).
Amongst other use cases, the new gravityflow_entry_url_inbox_table filter of this PR makes it possible to have partial entries link back to the initial form instead of an entry detail view - very useful when a form has multiple pages and many fields for initial submission.
- Activate partial entries add-on of Gravity Forms
- Setup a form to enable partial …
=> Add filter gravityflow_entry_url_inbox_table to support partial entries

change_log.txt, includes/steps/class-step-approval.php
See [HS#10674](https://secure.helpscout.net/conversation/936611609/10674?folderId=1776095)
This PR adds the filter gravityflow_approval_revert_step_id to enable customization of what step the revert option sends a workflow to during an approval step.
- Change to the PR branch
- Create a form + workflow with at least an approval step, user input step and one other step.
- Setup the approval step to have revert option active and pointing to the user input step.
- Use a filter similar to the one below customized to your step IDs
- Submit form and verify that when clicking 'revert' on approval step it goes to the expected step.
```
add_filter( 'gravityflow_approval_revert_step_id', 'sh_gravityflow_step_revert_control', 10, 4 );
function …
```
=> Add filter gravityflow_approval_revert_step_id

change_log.txt, class-gravity-flow.php, includes/steps/class-step.php
See [HS#10486](https://secure.helpscout.net/conversation/932770262/10509/)
This PR adds the filter gravityflow_step_is_condition_met and customizes the logic within the is_condition_met function. Prior to this PR:
- You were limited to a single ANY (or) / ALL (and) set of conditions for enabling condition
- If you wanted to evaluate step conditions through code, you had to set a known false conditional setting in order to evaluate through [gform_is_value_match](https://docs.gravityforms.com/gform_is_value_match/).
-Switch to the PR branch in your local environment
-Create a form with 2 workflow steps - 1 with conditional setting and 1 without
-Add the a variation of the following snippet to your functions.php file. This one assumes some step, form and field IDs but …
=> Support step specific complex conditional logic

change_log.txt, includes/pages/class-status.php
Resolves issue introduced via #269 
**Test Instructions:**
- Switch between master and this branch
- See that the extra/default search box in filter area is not displayed.
- Verify that [gravityflow_form_ids_status](https://docs.gravityflow.io/article/205-gravityflowformidsstatus) continues to show filtered values for all/pending/complete/cancelled.
=> Remove status page default search box display

change_log.txt, class-gravity-flow.php, includes/steps/class-step.php
re: [HS#10854](https://secure.helpscout.net/conversation/955270281/10854?folderId=1776095)
Adds a filter gravityflow_timeline_note_add to both step and gravityflow() scenarios allowing developers to customize if, and what the message would be, for timeline notes.
- Switch to this PR branch
- Add a snippet similar to the following
```
add_filter( 'gravityflow_timeline_note_add', 'timeline_note_step_only', 10, 5 );
function timeline_note_step_only( $note, $entry_id, $user_id, $user_name, $step ) {
if ( ! $step ) {
return false;
}
return $note;
}
```
- Notice how only step actions (not restart workflow for example) are not included in the timeline.
- Test that changing the $note content also updates with revised text.
=> Adding gravityflow_timeline_note_add filter

change_log.txt, includes/class-common.php
re: [HS#10855](https://secure.helpscout.net/conversation/955303810/10855?folderId=1776095)
Adds a filter gravityflow_timeline_notes filter to allow developers to customize the order, amount and content for timeline notes.
- Switch to this PR branch
- Add a snippet similar to the following
```
add_filter( 'gravityflow_timeline_notes', 'jo_timeline_reverse', 10, 2 );
function jo_timeline_reverse( $notes, $entry ) {
$notes = array_reverse( $notes );
return $notes;
}
```
- Notice how the notes are in chronological order.
- Test that other changes to contents of $notes via code are applied as expected.
=> Adding gravityflow_timeline_notes filter 

class-gravity-flow.php
Updates `Gravity_Flow::maybe_delay_workflow()` to support delaying workflow processing for PayPal Standard, Stripe 3.1, and future `GFPaymentAddOn` based add-ons which add delayed payment support.
Also overrides the new `action_trigger_payment_delayed_feeds` method so it will trigger the workflow and updates the existing `paypal_fulfillment` method to use it.
=> Support the delayed payment enhancements in GF 2.4.13

includes/steps/class-step-feed-post-creation.php
re: [HS#9865](https://secure.helpscout.net/conversation/888930716/9865/)
Updates the APC step to prevent the view more link being output for the discussion field when the feed is being processed.
- Add code snippet:
```
add_filter( 'gravityflow_discussion_items_display_limit', function () {
return 1;
} );
```
- Create a form with a discussion field
- Add an APC feed with the discussion field merge tag in the post content setting
- Add a User Input step with the discussion field as editable
- Add a APC step
- Submit form with value in discussion field
- On the UI step add another value to the discussion field
- View the post and find the view more link included in the discussion field output
- Repeat test and find the view more link in no longer included in the …
=> Suppress discussion field merge tag view more link for the APC add-on

class-gravity-flow.php
In Gravity Forms 2.4.12.3, the `gform_post_save_feed_settings` action hook was added. This allows for hooking into when a feed is saved in the wp-admin. The hook looks like this:
```php
/**
* Perform a custom action when a feed is saved.
*
* @param string  $feed_id 	The ID of the feed which was saved.
* @param int 	  $form_id 	The current form ID associated with the feed.
* @param array   $settings	An array containing the settings and mappings for the feed.
* @param GFAddOn $addon 	The current instance of the GFAddOn object which extends GFFeedAddOn or GFPaymentAddOn (i.e. GFCoupons, GF_User_Registration, GFStripe).
*
* @since 2.4.12.3
*/
do_action( 'gform_post_save_feed_settings', $result, $form_id, $settings, $this );
```
In Gravity Flow, the `Gravity_Flow` class extends `GFFeedAddOn`, …
=> Added gform_post_save_feed_settings hook

change_log.txt, includes/steps/class-common-step-settings.php, includes/steps/class-step.php, js/form-settings.js
See [HS #10520](https://secure.helpscout.net/conversation/933782946/10520?folderId=1113497)
This PR adds the option for CC: to be included for all notification types of Gravity Flow (assignee, approval, rejection, complete). It does not currently evaluate whether [gform_notification_enable_cc](https://docs.gravityforms.com/gform_notification_enable_cc/) filter has been set or not. Perhaps worth discussion whether it should, or a Gravity Flow filter that includes step-specific parameters.
- Enable the dev-notification-cc branch
- Test that all notification types include an option for CC: distribution
- Confirm that notifications deliver with CC: users/emails specified
=> Extend settings + UI to always show CC field

change_log.txt, js/form-settings.js
See [HS#10838](https://secure.helpscout.net/conversation/953450944/10838?folderId=1776095)
This PR adds the same Workflow merge tag options to the Revert notification tab as the assignee, approval/rejection tabs already provide.
- Create a form with approval + user input step.
- Select the 'Revert to User Input step' option to associate user input step.
- Verify that the merge tag dropdown on revert tab for notification message does not include workflow options.
- Switch to the fix-10838-revert-merge-tags branch.
- Review step settings to confirm that merge tag dropdown does include workflow options.
=> Added workflow options to merge tag dropdown for revert notification

includes/steps/class-step-user-input.php
RE: [HS #11095](https://secure.helpscout.net/conversation/976249748/11095?folderId=3106366)
This PR adds a check to see if the confirmation message on a user input step is empty. Currently if the confirmation is enabled via the checkbox and left empty the assignee of the user input step will receive an error "There was a problem while updating the assignee status." when completing the step.
- Import the form from Subrato's note, make sure the user input step is set to assign the user selected in the dropdown field on the form and the the confirmation in the user input step is empty.
- Preview and submit the form using your user as the selected value in the dropdown.
- View the user input step for the entry and complete it, find that you receive the above mentioned error.
- Edit the user …
=> Fix incorrect feedback when User Input step confirmation is empty

change_log.txt, class-gravity-flow.php
re:[HS#10021](https://secure.helpscout.net/conversation/904617410/10021?folderId=2308452)
This PR fixes an issue when `GVCommon::check_entry_display()` returns a `WP_Error` object, a PHP fatal error would be thrown in the `filter_gravityview_common_get_entry_check_entry_display()` method.
The customer provides some possible scenarios to reproduce it but we couldn't get the expected results. However, since `GVCommon::check_entry_display()` indeed returns `WP_Error` if the entry is not valid according to the view search filters, it makes sense to update our code as the PR proposed.
=> Fix PHP fatal error thrown in the filter_gravityview_common_get_entry_check_entry_display() method

change_log.txt, class-gravity-flow.php
re:[HS#11058](https://secure.helpscout.net/conversation/974045212/11058?folderId=1113492)
This PR fixes an issue where PHP fatal error is thrown when processing expired entries with steps that no longer exist.
This is a fix that we add based on the PHP fatal error message the ticket provided. We don't seem to find an easy way to reproduce the error at our end.
=> Fix PHP fatal error thrown when processing expired entries with steps that no longer exist

css/form-settings.css
RE: [HS 11234](https://secure.helpscout.net/conversation/988660276/11234?folderId=3106366)
This PR addresses an issue where at smaller browser resolutions the multi-select field in a user input step using the "Conditional Routing" option the multi-select used under the "Editable Fields" heading would shrink to a very small size. Changes in this branch add a minimum width to the field to prevent shrinking as other input fields in the same location do not fluidly change based on width.
- Create a form and add a user input step or open a user input step on a pre-existing form.
- Toggle the "Conditional Routing" option for the "Assign To:" section of the step.
- Shrink your browser to a smaller size and notice that the multi-select field under "Editable Fields" will shrink to a very small …
=> Fix shrinking multi-select in user input step routing at smaller resolutions

class-gravity-flow.php
re: [HS#11327](https://secure.helpscout.net/conversation/992967478/11327/)
This updates our `gform_is_value_match` filter callback so it only checks the type property if `$source_field` is a field object preventing the following PHP notice.
> Notice: Trying to get property 'type' of non-object in /app/public/wp-content/plugins/gravityflow/class-gravity-flow.php on line 8282
- Add the following code snippet
- Create a page and add the [gflow_notice_test] shortcode
- With master view page and find the notice occurs
- With this branch find the notice does not occur
```
add_shortcode( 'gflow_notice_test', function () {
echo '<h3>notice test</h3>';
printf( '<p>not a field - match: %s</p>', var_export( GFFormsModel::is_value_match( 'test', 'test', 'is', array( 'not a field' ) ), true ) ); …
```
=> Fix a PHP notice which can occur during conditional logic evaluation

class-gravity-flow.php
re: [HS#11490](https://secure.helpscout.net/conversation/1001284230/11490?folderId=1113492)
Fixes an issue where the "Restart Workflow" choice is missing from the Status page bulk actions drop down when the Members plugin is used to enable the Gravity Forms and Gravity Flow capabilities for a role.
- With the Members plugin deactivated find that the "Restart Workflow" choice is included in the Status page bulk actions drop down
- Enable Members and enable the Gravity Forms and Gravity Flow capabilities for your role
- Visit the Status page and find the choice is missing
- Switch to this branch 
- Enable the "Status - Admin Actions" capability in Members for your role
- Return to the Status page and find the "Restart Workflow" choice is now available
=> Add the gravityflow_admin_actions cap to Members

js/form-settings.js
RE: [HS #11292](https://secure.helpscout.net/conversation/990291660/11292?folderId=3106366)
Currently workflow merge tags are missing from the merge tag dropdown when editing certain notification types in a step, specifically the "In Progress" and "Complete" types. This PR adds support for making the merge tags available in the merge tag dropdown for these types.
- Create and form, add a new user input step, activate the save progress functionality.
- Tab into the In Progress notification, select the merge tag dropdown and find there are no workflow merge tags available. Do the same for the complete notification and find this is also the case.
- Switch to this branch, perform the same test, find that the merge tags are available in the merge tag dropdown for both of the above listed …
=> Add workflow merge tags to merge tag dropdown for certain step notifications

.github/pull_request_template.md
See [Github Docs](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository#adding-a-pull-request-template)
Initial draft provides shell sections/questions that appear to be common from most of existing PRs.
If this does add value, the same folder/PR template could be applied to the other add-ons. There currently is not a way to define a template at an org level with Github.
=> Add .github folder with default PR template

change_log.txt, class-gravity-flow.php
See [HS#11203](https://secure.helpscout.net/conversation/986273684/11203?folderId=1776095)
Viewing the step list does inform users that a step type used within their workflow is currently missing - be it for inactive plugin, plugin permissions issue on server or other reasons.
However, the user can still attempt to edit step settings (or bookmarked edit link) and encounter the following error, "Fatal error: Call to a member function get_type() on boolean in /var/www/html/myintranet3-jperlman.dawsoncollege.qc.ca/wp-content/plugins/gravityflow/class-gravity-flow.php on line 1331"
This PR addresses by adding additional boolean check and displaying a reasonable error through wp_die.
- Create form + workflow with steps from add-ons in addition to Gravity Flow
- …
=> Enhance checking step exists before edit step settings / feed add-on

change_log.txt, includes/steps/class-step-approval.php
[See HS#11186](https://secure.helpscout.net/conversation/984454562/11186?folderId=1776095)
Resolving an issue where an approval step being selected to revert where the workflow note is required will not have the expected note included via {workflow_note} in the revert notification.
- Start from master branch
- Create form with an user input step
- Add an approval step with revert set + workflow note required.
- Ensure the revert notification is setup and includes {workflow_note} merge tag.
- Process the workflow. Select the revert option and provide a workflow note.
- The notification will not include that note, but may have any previous step notes.
- Switch to fix-11186-revert-notes branch
- Re-test and note that the correct note is included.
None required
None required
=> Update revert notification timing to capture correct workflow note

includes/steps/class-step-feed-wp-e-signature.php
RE: [HS #10868 ](https://secure.helpscout.net/conversation/957146571/10868?folderId=3106366)
Currently if users are using the WP E Signature add-on to handle assignment order for signatures (basically when the user who first signs the document saves the document, it generates a second document for an approval signer to sign) the signature step in Gravity Flow will end when any signature is saved, so in this case when the initial signer completes signing, the workflow continues despite another signature being required before the document is "closed" and the workflow should continue to the next step.
This PR just changes what we're hooking our code when wrapping up the signature step, currently we use a hook that will run whenever any signature is saved, when more than one signature is …
=> Change hook used when ending signature step

includes/class-gravityview-detail-link.php
`GravityView_Field::field_options` has a 5th parameter called `$form_id` since GravityView 2.5
https://github.com/gravityview/GravityView/commit/5e6af4d6ce087e0d199f520159d0814172500b3b
=> Prevent signature warning with GravityView 2.5

class-gravity-flow.php, includes/steps/class-step.php, tests/unit-tests/gravity-flow-step/test-get-timestamp-delay.php
re: [HS#12377](https://secure.helpscout.net/conversation/1052794336/12377/)
This updates `Gravity_Flow::shortcode()` to use `get_post_type()` instead of `get_post()->post_type` to fix a PHP notice which can occur if `get_post()` does not return a post object.
> PHP Notice: Trying to get property 'post_type' of non-object in class-gravity-flow.php on line 6046
It also updates `Gravity_Flow_Step::get_timestamp_delay()` to trim the value of the offset setting and only adjust the timestamp when the remaining value is numeric.  This fixes PHP warnings which can occur if the offset setting does not contain a numeric value or contains additional non-numeric characters.
>  PHP Warning: A non-numeric value encountered in class-step.php on line 901
- Configure the inbox page shortcode with the …
=> Fix PHP warning and notice

js/entry-detail.js
Refer to [HS #11171](https://secure.helpscout.net/conversation/982861014/11171?folderId=1113492)
Issue pertains to inability to properly click through the Discussion Field view more/less when using Safari browser on Mac or iPhone.
- Create a form with discussion field
- Create user inputs steps that have the discussion field as editable. Either use [gravityflow_discussion_items_display_limit](https://docs.gravityflow.io/article/188-gravityflowdiscussionitemsdisplaylimit) to reduce # of steps required (default of 10), use admin actions to return workflow to a single user input step, or have 10+ steps in workflow.
- Using Safari note that when the display limit has been passed the view more/less JS clickable link does not show/hide entries as expected
- Change to this PR branch and re-test. …
=> fix-11171-view-more-safari

.travis.yml, class-gravity-flow.php, includes/steps/class-step.php
- Fixes a notice which occurs on any page where the form `id` query arg is not being used.
```
[01-Feb-2020 13:48:26 UTC] PHP Notice:  Trying to access array offset on value of type bool in /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-content/plugins/gravityflow/class-gravity-flow.php on line 566
[01-Feb-2020 13:48:26 UTC] PHP Stack trace:
[01-Feb-2020 13:48:26 UTC] PHP   1. {main}() /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-admin/index.php:0
[01-Feb-2020 13:48:26 UTC] PHP   2. include() /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-admin/index.php:111
[01-Feb-2020 13:48:26 UTC] PHP   3. do_action() /Users/richard/LocalBetaSites/gravity-flow/app/public/wp-admin/admin-header.php:104
[01-Feb-2020 13:48:26 UTC] PHP   4. WP_Hook->do_action() …
```
=> Fix PHP 7.4 issues

change_log.txt, includes/steps/class-step-webhook.php
Enhance the outgoing webhook to allow the use of shortcodes such as [conditionals](https://docs.gravityforms.com/conditional-shortcode/) within the raw body structure. In order for a similar change to be applied through the field mapping setting, Gravity Forms issue #807 will have to be addressed regarding parsing " within the generic_map settings field type.
- Create a form/workflow involving outgoing webhook
- Use the [conditional shortcode](https://docs.gravityforms.com/conditional-shortcode/) for content such as
```
[gravityforms action="conditional" merge_tag="{Number:1}" condition="greater_than" value="10"]
"dynamic-key": "would only be displayed when field 1 > 10",
[/gravityforms]
```
- Note that master branch does not evaluate the shortcode although the merge tag within it is.
- …
=> Add shortcode processing to outgoing webhook raw body requests

change_log.txt, includes/pages/class-print-entries.php
[See HS 11995](https://secure.helpscout.net/conversation/1027314490/11995?folderId=1776095)
The [gravityflow_print_styles](https://docs.gravityflow.io/article/52-gravityflowprintstyles) docs referenced a 2nd parameter which did not exist. This PR provides 
- Checkout master branch and attempt any use of gravityflow_print_styles filter that involves entry/form specific logic. Note that this can be called both from an entry details screen or from the bulk selection for print multiple entries. Insufficient parameters exist to do form/entry specific print styles.
- Switch to fix-11995-print-styles-filter branch and use an equivalent filter to the following
```
add_filter( 'gravityflow_print_styles', 'add_styles', 10, 2 ); 
function add_styles( $value, $entry_ids) {    
$customize = false;
if …
```
=> Update filter parameters, docblock and change_log

includes/steps/class-step-feed-dropbox.php
re: [HS#12616](https://secure.helpscout.net/conversation/1074719848/12616?folderId=1113492)
This fixes an issue where the Dropbox step does not complete when files are uploaded to  Dropbox. 
The issue was introduced by Dropbox Add-On version 2.4.1 which switched to passing only the feed ID in the processing request instead of the entire feed. As the add-on is now retreiving a clean version of the feed from the database the `workflow_step` property the step added to the feed meta is lost.
The Dropbox step now stashes the step id in custom entry meta which is retreived when the gform_dropbox_post_upload hook is triggered and used to determine if the step should be completed.
- Create a form with a file upload or Dropbox upload field
- Create Dropbox feed
- Create Dropbox step
- Create …
=> Fix workflows stalling on the Dropbox step

change_log.txt, includes/steps/class-step-update-user.php
re: [HS#12938](https://secure.helpscout.net/conversation/1103134466/12938?folderId=2308452)
This PR adds a workflow note when the Update User step is completed. Previously the notes only added when the step failed.
Set up a Update User step in your workflow. With the `master` branch there isn't any note added to the workflow timeline or entry notes if the step is successfully completed. Switch to this branch you'll be able to see the note added.
No.
https://www.dropbox.com/s/m1prht9uyyzz9yu/Screenshot%202020-03-14%2015.41.46.png?dl=0
No.
=> Add workflow note when the Update User step is completed

change_log.txt, class-gravity-flow.php, includes/pages/class-reports.php
This PR adds new Security Options to allow the reports chart can be displayed with the reports shortcode.
1. Enable the "Allow the Reports shortcode to display workflow reports." setting. View the page with the reports shortcode as an anonymous user, reports would be displayed; if not checking this option, you'll see "You don't have permission to view this page."
2. Users with the `gravityflow_reports` cap can see the reports chart regardless of the setting.
No.
1. Update the [shortcode](https://docs.gravityflow.io/article/36-the-shortcode) documentation, update the screenshot of the Security Options.
2. Add a new doc for the `gravityflow_reports_args` filter. Code example:
```
/**
* Force to check permission if it's the report for a certain form.
*
* @param array $args The arguments.
*
* …
```
=> Setting to allow the reports shortcode

change_log.txt, class-gravity-flow.php, js/entry-detail.js
See [HS 11171](https://secure.helpscout.net/conversation/982861014/11171?folderId=1113497). The Discussion Field View More/Less feature displays visually on the Form > Entries screen of core GForms, but the click events are not executing due to the different markup structure of where/how the field is being rendered.
- Create a form with discussion field.
- Add a workflow with a user input step that includes the save in progress setting.
- Submit discussion field values 10 times, or alternatively you can use [gravityflow_discussion_items_display_limit](https://docs.gravityflow.io/article/180-gravityflowdiscussionitemsdisplaylimit) and a lower number to trigger the view more/less effect.
- Confirm that on Form > Entries screen when viewing or editing the entry the effect does not work.
- …
=> Refine discussion view more/less JS to execute in multiple page contexts

class-gravity-flow.php, tests/unit-tests/gravity-flow/test-has-shortcode-or-block.php
This was prompted by a Gravity Forms ticket reporting that a form using conditional logic does not function when located in a reusable block. It was discovered that the methods used to determine if the posts for the current WP query contain the shortocode or block were not checking the contents of reusable blocks which are stored as separate posts. This issue prevented the required scripts and styles being enqueued correctly. 
This adds `Gravity_Flow::has_shortcode_or_block()` and updates `Gravity_Flow::look_for_shortcode()` so that the post content for reusable blocks is also checked when determining if the scripts and styles need to be enqueued.
- Create a page with the Workflow Inbox block
- Click the block options icon and select the "Add to Reusable Blocks" choice
- Enter a name and …
=> Fix missing scripts and styles when using reusable block

change_log.txt, includes/steps/class-step-feed-hubspot.php
This fixes the issue of duplicate HubSpot steps. The issue of having steps displayed for both Gravity Forms Hub Spot Add-on and the third party Hub Spot Add-on is resolved.
- Install the Offical Gravity Forms Hub Spot Add-on.
- Install the third-party Gravity Forms Hub Spot Add-on: https://wordpress.org/plugins/gravityforms-hubspot/
- Activate only the Official Gravity Forms Hub Spot Add-on and check workflow step only consists of this one and not the other.
- Activate only the third-party Gravity Forms Hub Spot Add-on and check workflow step only consists of this one and not the other.
- Activate both Add-ons and check workflow step contains both.
N/A
N/A
N/A
=> Fix Duplicate HubSpot Step

change_log.txt, js/form-settings.js
This is a bug fix for the 'Schedule expiration' selection on a Workflow Step, as described on HS# [12355](https://secure.helpscout.net/conversation/1050698455/12355?folderId=3509658#thread-2970402028).
'Next Step if Expired' should appear only when 'Status after expiration' is selected as 'Expired'.
- Create a Workflow Step and enable 'Schedule expiration'.
- Select 'Status after expiration' as 'Expired', the option 'Next Step if Expired' should appear.
- Select 'Status after expiration' as 'Approved', the option 'Next Step if Expired' should not appear.
- Select 'Status after expiration' as 'Rejected', the option 'Next Step if Expired' should not appear.
N/A
Recording before the update: https://share.getcloudapp.com/wbukYdmp
Recording after the update: …
=> 12355 : Fix Expiration Status

includes/steps/class-step-feed-zapier.php
This updates the Zapier step to support processing feeds for the famework version of the add-on. As the feed IDs change during the migration the steps will also be updated at the end of the migration to ensure selected feeds will continue to be processed by the step.
- Use this branch and Zapier master branch (v3.2.1)
- Create a form with a Zapier feed
- Configure a workflow with an Approval step and a Zapier step
- Test the form to confirm the zap is only processed after the Approval step
- Update to the Zapier 4.0 branch (v4.0-beta-1.1)
- Check the Zapier step to confirm the feed is selected
- Test the form again to confirm the zap is only processed after the Approval step
- Check a form which does not have a Zapier feed to confirm Zapier is not an available type when creating a new …
=> Add support for Zapier Add-On v4.0

change_log.txt, class-gravity-flow.php
Added Support for Merge Tags on Workflow Step Conditions
https://secure.helpscout.net/conversation/1147238931/13378?folderId=516731
On a workflow step add a 'Step Condition' with a merge tag, say the value on field ID 1 is {form_id}. If the form_id is 17, on processing the form this workflow step should only process when the value entered on field ID 1 is 17. For all other values, this workflow step will not run.
N/A
N/A
N/A
=> Support for Merge Tags on Workflow Step Conditions

includes/pages/class-status.php
This was reported to me directly in RG Slack. When ForGravity Advanced Permissions uses the gravityflow_status_filter to return an array of form IDs which the current user can access the field filters drop down does not appear when a form is selected.
- Add code snippet updating the form IDs to match a few of those available on your site
```
add_filter( 'gravityflow_status_filter', function ( $args ) {
$args['form_id'] = array( 3, 4, 5 );
return $args;
} );
```
- Visit the Status page and in the filters select a form
- Find the field filters drop down does not appear
- Reload page and find the fields drop down does appear when a form is selected
- Modify the code snippet to `$args['form_id'] = 3;` or any other valid form id on your site
- Reload page and find the …
=> Fix missing status page field filters when form id constraint is an array

change_log.txt, includes/integrations/class-partial-entries.php
This fixes the case when a blank form appears for the partial entry step when the partial entry was already submitted.
Reference HelpScout ticket: https://secure.helpscout.net/conversation/1150735023/13425?folderId=1113492
To replicate the issue use the partial entry link to complete the entry.
Then, use the same link again and a blank form will show up.
After this update, it will show a message "This partial entry was already completed!" instead of the blank form.
N/A
N/A
N/A
=> Fix Blank Form for a Partial Entry already completed

change_log.txt, includes/class-connected-apps.php
Bugfix for [HS# 13500](https://secure.helpscout.net/conversation/1159586921/13500?folderId=3509658): 
Issue on the class `Gravity_Flow_Connected_Apps` (located in includes/class-connected-apps.php).
[L119](https://github.com/gravityflow/gravityflow/blob/master/includes/class-connected-apps.php#L119) compares to 'Authorize App' but a translated text maybe sent via the button text located on [L703-705](https://github.com/gravityflow/gravityflow/blob/master/includes/class-connected-apps.php#L703,L705).
To test 'Authorize App' for different translations on the 'Connected Apps' settings for Gravity Flow.
N/A
N/A
N/A
=> Fix : Connected App Translation Text

change_log.txt, includes/steps/class-step-user-input.php
HelpScout# [13389](https://secure.helpscout.net/conversation/1148375877/13389?folderId=3509658#thread-3266957410)
Added the call to `gform_pre_validation` on User Input Step for Pre Validation on the User Input Workflow Step.
To be tested with customer's [form](https://secure.helpscout.net/conversation/1148375877/13389?folderId=3509658#thread-3270096961) and custom GravityPerks e-commerce field [snippet](https://gist.github.com/spivurno/7356056) adding a Calculated Shipping field to the form.
To add a Calculation field to the form and set it as the “field_id” in the snippet config. It will automatically be converted to a shipping field on submission.
N/A
N/A
N/A
=> Form Pre Validation on the User Input Step

class-gravity-flow.php
The latest version of GravityView's Advanced Filter uses a new search filter object structure and a different filter (`gravityview/adv_filter/filters` instead of `gravityview_search_criteria`) to modify it, so integration with this extension no longer works.
Create an approval workflow, add a new form submission, add a new GravityView View and configure an advanced filter using `Workflow Assignee` as a criterion.
=> Add support for GravityView's Advanced Filter v2.x

change_log.txt, includes/steps/class-step-approval.php, js/step-approval.js
When 'Require Confirmation' step setting for Approval step is active, the approve/reject options get an added browser default JS confirmation prompt before accepting the chosen selection. This should also apply when a revert (to user input step) option exists.
[Trello reference link](https://trello.com/c/0pxmd7WQ/519-approval-step-require-confirmation-apply-to-revert-prompt)
Create a workflow with User Input and Approval Steps. On the Approval step, enable the following setting:
On clicking 'Revert' on the Approval step, the confirmation box pop up should appear.
N/A
N/A
N/A
=> Approval Step - Require Confirmation apply to revert prompt

class-gravity-flow.php
re: HS[#13809](https://secure.helpscout.net/conversation/1188384647/13809?folderId=1113492)
This updates Gravity Flow in parallel to [Form Connector PR #38](https://github.com/gravityflow/gravityflowformconnector/pull/38) to address a fatal error which occurs when merge tag processing runs during evaluation of conditional logic. 
See instructions in [Form Connector PR #38](https://github.com/gravityflow/gravityflowformconnector/pull/38)
=> Fix a fatal error during merge tag replacement with Form Connector

js/reports.js, tests/acceptance-tests/acceptance/0043ReportsShortcodeCept.php
This PR fixes an issue where the "Step Assignees" dropdown was missing from the Reports shortcode when "Category" is set to "Step" and a step is chosen. The issue also happened in the Workflow Reports page in WP Dashboard.
1. Go to your Workflow Reports in WP Dashboard. Select a form, set the Category to Step, select a Step, and the assignee dropdown won't show up if you're on the `master` branch. Switch to this branch and it'll work.
2. Use the shortcode `[gravityflow page="reports"]` to display the Reports in a Page. Repeat the above steps.
Update test `0043ReportsShortcodeCept.php` to include a validation of the dropdown display.
=> Fix the reports step assignees dropdown missing issue

change_log.txt, includes/steps/class-step-feed-user-registration.php
re: [HS#14111](https://secure.helpscout.net/conversation/1222275682/14111/)
Adding filter before `process_feed` to disable email when User Activation setting on the User Registration feed is set to 'manual'.
Adding check for the `userActivationValue` on the feed meta when processing the filter to disable email on the 'manual' scenario.
- See: HS#14111](https://secure.helpscout.net/conversation/1222275682/14111/#thread-3498041731)
- With this branch, check the user activation email link sent normally when User Activation on User Registration Feed settings is set to 'by email from WordPress'.
- Next, check the user activation email link is not sent when the User Activation setting is set to 'manually'.
N/A
N/A
N/A
=> Fix user auto receiving activation email with Manual User Activation on User Registration Feed

.travis.yml
This updates the Travis CI config to use the correct version of PHPUnit for the PHP version the tests are running on. [Gravity Forms made similar changes recently](https://github.com/gravityforms/gravityforms/pull/1180/commits/b8d94367ebc801110be8dea6734f9973cbf24a78).
Here is the failing test on master: https://travis-ci.com/github/gravityflow/gravityflow/builds/180872802
The tests are now passing on this branch: https://travis-ci.com/github/gravityflow/gravityflow/builds/180991459
N/A
N/A
N/A
=> Fix the unit tests for WP 5.5 and PHP 5.6

change_log.txt, class-gravity-flow.php
re: [slack thread](https://gravityflow.slack.com/archives/G7C6W4PD1/p1597758590004500)
This uses the `query_vars` filter to remove `page` from the array of query variables when accessing the front-end inbox and detail pages with WordPress 5.5+. This prevents the page var triggering a 404 error.
- Use the inbox shortcode in a page and set that page as the front page in the wp general settings
- View the page and click on an entry
- Find a 404 not found occurs
- View the page and click on an entry
- Find the detail page is displayed
- Test accessing the entry from the status page
- Test the block
- Enable the back link on the shortcode and/or block
- Test the inbox is displayed when using the back link on the detail page
N/A
N/A
N/A
=> Remove page query var for inbox/detail pages

change_log.txt, includes/EDD_SL_Plugin_Updater.php
`Gravity_Flow_EDD_SL_Plugin_Updater` has been updated to `EDD_SL_Plugin_Updater` v1.7.1. This adds support for the WP 5.5 automatic updates feature avaialable on the plugins page.
- With master visit the plugins page and notice the Gravity Flow row does not include the enable or disable automatic updates link
- Reload the page to find the link is now available
- Change the plugin version number in gravityflow.php to 2.5.11-dev
- Reload the page to find an update is available
- Click the view details link to confirm the changelog modal is displayed and contains the changelog for version 2.5.11
N/A
N/A
N/A
=> Update the EDD SL updater to v1.7.1

change_log.txt, includes/assignees/class-assignee.php
RE: [HS#14496](https://secure.helpscout.net/conversation/1260478325/14496?folderId=3509658#thread-3618865023)
Submit button missing on FE workflow step for role-based user assignment, with the following shortcode:
`[gravityflow page="inbox" sidebar="false" workflow_info="false" step_status="false"]`
1. Create a workflow and select assignee by role.
2. Create a front-end page with the above shortcode.
3. Open the inbox entry from the front-end page, submit button would be missing.
4. Switch to this branch and see if the submit button is available now.
N/A
N/A
N/A
=> Fixed missing Submit button on FE for role-based assignee

class-gravity-flow.php, gravityflow.php, includes/wizard/steps/class-iw-step-updates.php
This fixes an issue where the auto-updates link on the installed plugins page and our background updates setting can get out of sync.
- With master toggle the enable/disable auto-updates link on the installed plugins page
- Go to the workflow settings page to find the background updates setting did not change
- Change and save the setting
- Return to the installed plugins page to find the auto-updates link was not updated
- Repeat above tests to confirm using the link on the installed plugins page updates our setting and vice versa
- Install the plugin on a new site
- Find auto-updates are enabled on the installed plugins page
- Go to one of our admin pages to trigger the installation wizard, disable updates during the wizard
- Go to the installed plugins page to …
=> Sync the WP5.5 auto-updates state and the app background updates setting

class-gravity-flow.php, includes/wizard/steps/class-iw-step-pages.php, includes/wizard/steps/class-iw-step-updates.php
This updates the strings related to background updates on the installation wizard and workflow settings pages to use "automatic updates" to match the nomenclature used by WordPress 5.5.
The following article will need updating with the above screenshots: https://docs.gravityflow.io/article/159-how-to-install-gravity-flow
=> Update background updates strings

change_log.txt, includes/steps/class-step.php
Re: [Issue#41](https://github.com/gravityflow/backlog/issues/41)
1. Create a form with a User Input step and select Step Assignees, and try to save step settings.
(Alternatively can use the form export attached on the Issue page).
2. Saving the step settings will result in a fatal error.
3. Switch to this branch, and then repeat step 1.
4. Step settings success.
5. Test the workflow to confirm everything works as expected.
N/A
N/A
N/A
=> Fix Fatal Error with Assignees on User Input Step

change_log.txt, class-gravity-flow.php
Re: [HS#14662](https://secure.helpscout.net/conversation/1274562929/14662/) to remove inbox count red bubble.
- After switching to this branch, add the filter call on functions.php:
`add_filter( 'gravityflow_inbox_count_display', '__return_false', 1 );`
- Refresh Wordpress Dashboard and confirm the filter count is no longer.
- Remove the filter call from functions.php, and check to see the inbox count value is back.
N/A
N/A
Add documentation for the filter `gravityflow_inbox_count_display`
`add_filter( 'gravityflow_inbox_count_display', '__return_false', 1 );`
Alternativey,
```
add_filter( 'gravityflow_inbox_count_display', 'sh_gravityflow_inbox_count_display', 10, 1 );
function sh_gravityflow_inbox_count_display( $show ) {
return false;
}
```
=> Added filter to remove inbox count

change_log.txt, class-gravity-flow.php
Re: [HS#14988](https://secure.helpscout.net/conversation/1299881912/14988/)
The issue with the inbox count updates slowing down the website. Updating the configuration so inbox count is disabled by default, and can be enabled with the filter `gravityflow_inbox_count_display`.
1. Update to this branch and check the inbox count value is now disabled.
2. Use the filter `add_filter( 'gravityflow_inbox_count_display', '__return_true', 1 );`, and confirm the inbox count value is enabled
N/A
N/A
N/A
=> Fix inbox count to be disabled by default

change_log.txt, includes/pages/class-status.php
Re: [#14868](https://secure.helpscout.net/conversation/1291017933/14868?folderId=1776095)
Custom columns defined through gravityflow_columns_status_table filter cannot be set to be sortable in current version of Gravity Flow. The introduction of gravityflow_sort_columns_status_table allows them to be provided they refer to an [entry_meta ](https://docs.gravityforms.com/gform_entry_meta/) or a field ID.
In order for truly custom values to be sorted, an update to **Gravity Forms** query parse function would be required and perhaps support for more than GF_Query::TYPE_DECIMAL - both of which are beyond the scope of this PR.
1. Switch to the feature-sort-status-columns branch of code
1. Place the [example_filters.txt](https://github.com/gravityflow/gravityflow/files/5352194/example_filters.txt …
=> Added gravityflow_sort_columns_status_table filter

change_log.txt, js/entry-detail.js
Re: [HS# 15018](https://secure.helpscout.net/conversation/1301980605/15018?folderId=1113492#thread-3748435873)
The popup 'An error occurred while printing' comes up with Firefox when the Print button is clicked on Workflow Details Page.
1. Update to this branch and check if the Print error is resolved with Firefox.
2. Confirm nothing breaks with other browsers (Chrome, Safari, IE, Edge).
N/A
N/A
N/A
=> Fix Print Error on Worflow Details Page with Firefox

change_log.txt, js/status-list.js
Re: HS# [15018](https://secure.helpscout.net/conversation/1301980605/15018?folderId=1113492#thread-3763622808)
The popup 'An error occurred while printing' comes up with Firefox when the Print button is clicked on front-end pages.
1. Update to this branch and check if the Print error is resolved with Firefox.
2. Confirm nothing breaks with other browsers (Chrome, Safari, IE, Edge).
N/A
N/A
N/A
=> Fix firefox print issue on front-end pages

change_log.txt, class-gravity-flow.php, includes/steps/class-step-user-input.php
Re: [HS#14607](https://secure.helpscout.net/conversation/1270186867/14607?folderId=1113492#thread-3788450740)
With Gravity View Entry Revisions, a successfully completed User Input Step on the workflow processes it's expiration step (when it should not).
1. Replicate the form and workflow settings as on the sandbox provided. Ensure Gravity View and Entry Revisions are enabled.
2. After the first step "Need Admin Response", the expiration step email is erroneously triggered.
3. Switch to this branch and repeat 2. This time, the erroneous email trigger doesn't happen,
With this update, entry revisions for User Input step will not be stored. Maybe this limitation or exception with Gravity View Entry Revisions can be updated [here](https://docs.gravityflow.io/article/30-integration-with-gravit …
=> Fix gravityview entry revision user input

change_log.txt, class-gravity-flow.php
Re: [HS# 14496](https://secure.helpscout.net/conversation/1277212685/14687?folderId=1113497#thread-3671826413)
An issue with the email assignee not reflecting approval (or move to the next step) on the Workflow Inbox front-end display.
1. Create a form with an email field, and any other field (say discussion)
2. Create a user input step with the email field as assignee, passing the workflow entry link merge tag via email.
3. Check the issue is resolved when working through the user input step.
N/A
N/A
N/A
=> Fix workflow showing same step on submission for email based assignee

change_log.txt, class-gravity-flow.php
Re: [HS# 15322](https://secure.helpscout.net/conversation/1325992575/15322?folderId=1113492#thread-3825730334)
When processing the step condition having a Form Submission step, the conditional logic wasn't evaluating properly, thus failing the entire workflow. The issue was the `$form_id` on `get_feed_condition_entry_meta()` was taken as the child `$form_id`. To fix this, we check if it's a `$parent_entry` and get the parent `$form_id`.
1. Use the testing form provided on the ticket.
2. Replicate the issue with `master`.
3. Switch to this branch and see the issue is resolved.
4. Test for other parent-child scenarios with the Form Connector plugin, like New Entry, etc.
N/A
N/A
N/A
=> Fix Step Condition having Form Submission Step fetching wrong entry meta

change_log.txt, includes/pages/class-status.php
[HS #15481](https://secure.helpscout.net/conversation/1343088308/15481?folderId=1776099)
The recently added gravityflow_sort_columns_status_table filter lets custom meta be defined as sortable columns for status views, but the default sort order cannot be customized. Plugin does not currently call [gform_get_entries_args_entry_list](https://docs.gravityforms.com/gform_get_entries_args_entry_list/#filter-entry-list-by-entry-meta) which would be the closest equivalent to allow that customization via Gravity Forms code. This PR creates gravityflow_sort_criteria_status to allow customization of the sort order for either initial page load or any constant alterations.
- Add the code from gist https://gist.github.com/Idealien/62c6cc2eece99e924bb6d4afd48c7452 to your environment
- Customize the 2 …
=> Add filter for customization of sort order incl. default page load

js/routing-setting.js
Reverting the addition of the gravityflow_routing_values_markup JS filter added in #368 for 2 reasons:
1.  It's possible to use the `gform_field_filters` PHP filter to remove the choice values  - forcing the textbox instead of the dropdown.
2. This component is likely to be refactored so it's best to wait until after the refactor before committing to filtering the markup.
Check for regressions. 
None.
=> Revert JS filter for routing values

css/form-settings.css
[Issue# 45](https://github.com/gravityflow/backlog/issues/45)
1. Enable Assignee Email "Send an email to the assignee" on a workflow step.
2. With Gravity Forms 2.4, the merge tag dropdown on the Message body does appear fine. It doesn't on Gravity Forms 2.5.
3. Update to this branch and check with both Gravity Forms 2.4, and Gravity Forms 2.5. Gravity Forms 2.4 should display the same. Gravity Forms 2.5 should now be fixed.
N/A
N/A
N/A
=> Fix assignee email merge tag dropdown with Gravity Forms 2.5

includes/class-extension.php, includes/class-feed-extension.php, includes/fields/class-fields.php
Addresses https://github.com/gravityflow/backlog/issues/59
Test the Workflow settings for both types of extensions and the form editor on Gravity Forms both 2.4 and 2.5.
=> Fix Gravity Forms namespaces

change_log.txt, css/form-settings.css
[Issue# 58](https://github.com/gravityflow/backlog/issues/58)
1. Enable Assignee Email "Send an email to the assignee" on a workflow step.
2. With Gravity Forms 2.4, the merge tag dropdown on the Message body does appear fine. It doesn't on Gravity Forms 2.5.
3. Update to this branch and check with both Gravity Forms 2.4 and Gravity Forms 2.5. Gravity Forms 2.4 should display the same. Gravity Forms 2.5 should now be fixed.
N/A
N/A
N/A
=> Fix assignee email merge tag location

includes/EDD_SL_Plugin_Updater.php
Closes gravityflow/backlog/issues/54
This updates `Gravity_Flow_EDD_SL_Plugin_Updater` with the changes from `EDD_SL_Plugin_Updater` v1.8.0.
- Change the version in gravityflow.php and an extension to older versions
- Go to the installed plugins page to find updates are available
- Click the view details links to confirm the changelog modal is displayed
N/A
N/A
N/A
=> Update the EDD SL updater to v1.8.0

change_log.txt, includes/steps/class-step.php
Providing a parallel action to gravityflow_step_complete for custom processing.
- Ensure that steps continue to start as normal
- Ensure that use of the new action is possible
```
add_action( 'gravityflow_step_start', 'custom_step_start_step_due_date', 10, 5 );
function custom_step_start_step_due_date( $step_id, $entry_id, $form_id, $status, $step ) {
error_log('The gravityflow_step_start action works');
}
```
- Create new developer page based on docblock.
```
/**
* Allows custom logic to be added when the step is started.
*
* @since 2.7.1
*
* @param int               $step_id    The ID of the completed step.
* @param int               $entry_id   The entry of the completed step.
* @param int               $form_id    The form of the completed step.
* @param string            $status …
```
=> Add gravityflow_step_start action

change_log.txt, class-gravity-flow.php, includes/steps/class-common-step-settings.php
The Message textarea for the Assignee Email in a Step was using the soon-to-be-deprecated 2.4 version of the editor. In Gravity Forms 2.5, the process for defining Settings Fields updated to move away from `visual_editor` and to a standardized `textarea` type. 
This fix simply updates the properties we send to the Settings API to use the `textarea` type along with `use_editor` to ensure it remains a WYSIWYG field. 
Additionally, Gravity Forms is expecting each field to be wrapped with a `div` with a combination of classes (`gform-settings-field gform-settings-field__{input type}` in order to inherit the correct styles. In this case, since this was a "tabbed" field in our UI, we were only setting the `gravityflow-tab-field` class on the field wrapper in our custom logic. This fix updates …
=> Master fix 67 update assignee email message to use 2.5 editor

class-gravity-flow.php, css/inbox.css
Gravity Forms 2.5 moved to using classes to style the nav toolbar. We need to add those same classes to Gravity Flow's instances of the toolbar to get the styles working again in that version.
* Load up the admin and go to any main Flow screen (inbox, checklist, folders etc)
* Confirm the nav displays correctly as in the screenshot below
=> Fix display of main admin nav with Gravity Forms 2.5

change_log.txt, css/entry-detail.css
Changes to GF in 2.5-rc1 updated the specificity of our font-awesome styles. This caused the Timeline icons to display much smaller, since their font-size property was being reset/overridden. This fix simply makes that selector more-specific, retaining its properties. 
Addresses issue 80: https://github.com/gravityflow/backlog/issues/80
1. Add a form with an Approval step. 
2. Submit the form, and Approve the step as an anonymous user so that the "Approval" icon displays instead of the user avatar.
3. Ensure the icon is the correct size, and no longer tiny.
**Correct Display**
=> Fix Display of Icons in Timeline View

class-gravity-flow.php, js/feed-list.js
This PR fixes a conflict that occurs due to how Gravity Flow forks the feed ordering method implemented in the Feed Add-On Framework.
Since Gravity Flow uses a custom action name but the same Feed Add-On Framework method name, I've updated the method to confirm the action is for Gravity Flow feed ordering before continuing processing.
I also added a nonce check for added security.
1. Create a form with at least two workflow steps.
2. On the Workflow Steps page, re-order the feeds.
- The AJAX response should be `[["ok"],200]`.
- When you reload the page, the order should match the new feed order.
=> Fix conflict with Feed Add-On Framework feed ordering functionality

class-gravity-flow.php, includes/class-extension.php, includes/class-feed-extension.php
Closes https://github.com/gravityflow/backlog/issues/88
Remove the redundant exclamation mark from the license nag ready for Gravity Forms 2.5.
Check the exclamation mark has been removed from the license nags for Gravity Flow plus the two types of extensions on both Gravity Forms 2.4 and 2.5.
N/A
Before
After
N/A
=> Remove exclamation mark from license nag

change_log.txt, includes/pages/class-status.php
Despite filtering form ids with `gravityflow_form_ids_status`, the Gravity Flow Status page does not fetch correct counts (All, Pending, Complete, Cancelled) when used with `gravityflow_status_filter`
1. Add snippet with `gravityflow_form_ids_status` to restrict the display of forms on the Status page:
```
add_filter( 'gravityflow_form_ids_status', 'sh_status_form_ids_explicit', 10, 2 );
function sh_status_form_ids_explicit( $form_ids, $search_criteria ) {
//Adjust array to your desired form IDs.
$form_ids = array(13,16);
return $form_ids;
}
```
2. Add snippet with `gravityflow_status_filter` to the Status page to display entries on a particular step, or with a particular final status.
```
add_filter( 'gravityflow_status_filter', 'sh_gravityflow_status_field_filter' );
function …
```
=> Fix 'gravityflow_form_ids_status' not fetching correct Status page counts with 'gravityflow_status_filter'

class-gravity-flow.php
This PR fixes an issue introduced in https://github.com/gravityflow/gravityflow/pull/400 where the settings can't be saved on Gravity Forms 2.4.
Check that settings can be saved on Gravity Forms 2.4 and 2.5.
=> Fix save settings for 2.4

includes/steps/class-step-feed-add-on.php, includes/steps/class-step-feed-zapier.php
This restores the ability to use the Zapier step with forms which don’t have Zapier feeds. It also adds a Form setting to the Zapier step settings so the user can select a different form as the source of the feeds to be processed by the step.
Zapier Add-On 4.1 will add support for Zapier storing the zap ID in the feed when created or updated. If the feed meta contains the `zapID` a link to view the zap on zapier.com will be included in a tooltip next to the feed name.
- Enable logging for the Zapier add-on
- Create a form with a text field
- Duplicate the form
- Enable display of feeds on the Forms > Settings > Zapier page, if not already enabled
- Using an API client such as Postman or Paw create a `POST` request for the `/wp-json/gf/v2/feeds` endpoint of your site. Use basic auth …
=> Add Form setting to Zapier step

change_log.txt, class-gravity-flow.php, includes/class-extension.php, includes/class-feed-extension.php
This PR fixes the Gravity Forms Uninstall Page for Gravity Flow extensions. Currently, the uninstall page does not display Uninstall buttons for Gravity Flow Extensions. Also, the names of the extensions aren't listed with the 'Gravity Flow' prefix.
This resolves [Issue#102](https://github.com/gravityflow/backlog/issues/102).
1. Check the Gravity Forms Uninstall page to see the display of Gravity Flow Extensions with `master`.
2. Switch to this branch and confirm the uninstall buttons for all extensions display and work fine.
3. Confirm the names of all the extensions are displayed with the 'Gravity Flow' prefix.
N/A
N/A
N/A
=> Fix extensions uninstall on Gravity Forms uninstall page

change_log.txt, class-gravity-flow.php
The Font Awesome libraries were not being loaded for shortcodes, so our quick actions would not display. This pr patches that! 
* Create a page and embed your inbox with quick actions enabled `[gravityflow page="inbox" actions_column="true"]`
* Confirm the quick actions icons are visible on the front end
=> Fix font awesome not loading for shortcodes

css/form-settings.css
This PR fixes CSS rules on the `form-settings.css` to fix some UI issues on Form Connector's 'Update Field' step. The SVGs that were overridden before to fix the add-remove icons are no longer needed. The `gform-filter-value` CSS rule was only indicated for `input` previously, it should also be identified for `select`.
This resolves [gravityflow/backlog#105](https://github.com/gravityflow/backlog/issues/105).
1. Install and Enable the 'Form Connector' extension.
2. Create a Workflow 'Update Fields' step.
3. Select 'Entry Lookup' -> 'Conditional Logic'.
4. Notice the Add-Remove icons displayed under the rules.
5. Select a field on the rule which will display a select on the value, for instance 'Status of a step'.
6. Notice the select field's size isn't aligned.
7. Switch to this branch, …
=> Fix UI on 'Update Fields' Workflow Step

change_log.txt, class-gravity-flow.php, css/form-settings.css
This PR fixes an issue with the entry filter setting where the settings are not saved on Gravity Forms 2.5 and another issue where conditions cannot be removed on either 2.4 or 2.5. It also adjusts the space available for the no conditions message to prevent the icon from being cut off on 2.5.
Fixes https://github.com/gravityflow/backlog/issues/121
1. Add an Update Fields step
2. Select a form
3. Select "Conditional logic" for the entry lookup setting.
4. Add conditions.
5. Save & notice the settings are not saved on 2.5
6. Add more conditions and save while on this branch to check that the settings are saved.
7. Remove conditions and save to check that the conditions are removed after saving.
Double-check that there are no related regressions for the functionality of this setting on both …
=> Fix entry filter setting

change_log.txt, css/entry-detail.css, css/form-settings.css
With Gravity Forms 2.5, the Workflow Entry Inbox displays fields with `legend` instead of `label`. The CSS rules for `green-triangle` are defined to work only with `label.gfield_label`, so the green triangle only displays on legacy forms.
This fix removes the specific `label.gfield_label` CSS rule to a generic `.gfield_label`. Thus it works for both label and legend tags.
This resolves [gravityflow/backlog#122](https://github.com/gravityflow/backlog/issues/122).
1. Create a form, ensure 'Enable legacy markup' is not enabled.
2. Create a User Input step, and select editable fields. Enable highlight editable fields with the 'Green Triangle' setting.
3. Run the form and create an entry.
4. Open the Workflow Inbox for the entry created. The green triangle would not display for the editable …
=> Fix Green Triangle not displaying for Editable Fields on User Input Step
